### ISSUE TITLE
Grammar issues re "Crime check station" script

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1939] opened 2020-08-16 00:16 UTC
## EDDI version in which issue is found
3.7.0

## Steps to reproduce
1. Incur a bounty and fine.
2. Drop near a station where you can pay them off.

## Expected
Text like:

>Momentary Discrepancy has returned to normal space in the vicinity of Outpost, Dzhanibekov Beacon. Information:  There are facilities at this station to clear your pending bounty and fine.

## Observed
Text like:

>Momentary Discrepancy has returned to normal space in the vicinity of Outpost, Dzhanibekov Beacon  Information:  There are facilities at this station to clear your pending bounty and fine and..

## Investigation
We should be usuing `List()` here: this is precisely what it is for.

**Comment by Hoodathunk** [comment] 2020-08-16 23:18
@richardbuckle I believe this a duplicate of Issue #1872 

"We should be usuing List() here: this is precisely what it is for."
Okay, Mr Grumpy, I will look into it. ;-)

Personally don't remember if these scripts predate the addition of `list()` as I only vaguely remember that function being slipped in. I will look into it.

**Comment by richardbuckle** [comment] 2020-08-17 00:36
Sorry for being grumpy.

**Closed as completed** 2020-10-26 01:28 UTC
Labels: 6. not up to spec
