### ISSUE TITLE
{DEC:EDDI ship transfer initiated distance} results Not set 

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2569] opened 2023-07-31 15:52 UTC
![Screenshot 2023-07-31 184853](https://github.com/EDCD/EDDI/assets/21980416/01c4c42c-897f-4d71-b474-2a315c079c6b)

**Comment by Tkael** [comment] 2023-07-31 18:21
Duplicate of #2567.

**Closed as not planned** 2023-07-31 18:21 UTC
