### ISSUE TITLE
There might be a bug with {DECINV:Ship total fuel tank capacity}

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2501] opened 2023-01-23 14:20 UTC
## What's Wrong (please be as specific as possible)
Every time I jump, my fuel calculation won't work because it gives an error calculating this variable

### Expected
[Describe what you expected to happen]
Give the correct max fuel capacity of the ship, all fuel tanks included

Used to work fine

**Comment by Tkael** [comment] 2023-01-24 08:08
Duplicate of #2482.

**Closed as completed by Tkael** 2023-01-24 08:08 UTC
Labels: duplicate
