### ISSUE TITLE
Landing pad report does not fire for certain stations

### ISSUE THREAD

**Issue by The1AndMany** [EDCD/EDDI#355] opened 2018-01-24 00:07 UTC
## EDDI version in which issue found
v.2.4.6-b2

## Steps to reproduce

1. Be granted docking permission at an affected station

## Expected
Assuming station isn't an outpost (although some of those are affected as well), EDDI should pause for 8 seconds then fire a landing pad report.

## Observed
Complete silence.

## Investigation
- EDDI is firing the "Docking permission granted" script properly and was still saying any debug text I added outside of the conditional statement checking whether the landing pad report would be appropriate.
- Hitting "Test Script" would result in silence, but if I append the arguments for `StationDetails()` to include the example station's system (Shinrarta Dezhra) it would work normally.
    - Not immediately relevant, but may be worth looking into
- Experimenting with plugging alternate stations into StationDetails() showed that the script worked fine most of the time, but some stations would not set the station variable properly, so all the conditional saw was a null value.
    - Tested by adding `Debug: {station.model}.` outside the conditional and using `StationDetails()` to load a station to test
        - This may not be as conclusive as a field test, but I can verify that field results for 3 different stations (The Oracle, Oort Orbital, and Obsidian Orbital) correspond with lab results
- Affected stations seem to all be in or near the Pleiades.
    - Examples that wouldn't fire: Moni's Hub, The Oracle, Oort Orbital, Cavalieri, Exodus Point
    - Disclaimer: I wasn't able to extensively test outside the Pleiades, as there are just too many stations to choose from, but Cleve Hub in Eravate and a couple I tested near Colonia fired properly.
- Not all stations in the Pleiades are affected.
    - Example that fired properly: Obsidian Orbital

## Speculation
- **Please take this speculation with some salt, as I'm a hobbyist programmer at best and don't actually know anything about C#.**
- `StationDetails()` may not be able to pull data for the affected stations, resulting in station.model not being set.
- I have no idea what is causing these particular stations to be affected.
    - It's almost certainly not based on the system itself, as Moni's Hub wouldn't fire but Obsidian Orbital would, despite them both being in Maia.
    - It's also probably not the "Under Repair" station status, as other stations are affected and some stations under repair are not.
    - I also don't think it has anything to do with the station model, as several models are affected, including at least one outpost.

**Comment by Tkael** [comment] 2018-01-24 04:46
This is a duplicate of #97. Moni's Hub doesn't exist in the server data that EDDI is referencing. 
Until we can redirect EDDI to a different data source, neither StationDetails(), SystemDetails(), and BodyDetails() will be completely reliable.
Closing as a duplicate, but we are aware of this issue. Thanks for reporting.

**Closed by Tkael** 2018-01-24 04:46 UTC
