### ISSUE TITLE
EDDI Force Closing

### ISSUE THREAD

**Issue by SupremeAnu** [EDCD/EDDI#2376] opened 2022-07-01 01:09 UTC
Hello, I'm running EDDI version 4.0.1 for Odyssey and it keeps crashing. I have set everything up with Ivona and it operates until it closes while I'm playing the game. This only happens when playing the game.
My specs are:
R9 3900X
RTX 2080 Super
32GB DDR4 3200MHZ

**Comment by Tkael** [comment] 2022-07-01 01:21
Hmm. Are you using VoiceAttack? Please send a copy of the .log files from `%appdata%/EDDI` and I can take a look for any crashes that EDDI has recorded.

**Comment by Tkael** [comment] 2022-07-01 01:23
Also, is this a new problem or an ongoing problem?

**Comment by SupremeAnu** [comment] 2022-07-01 01:29
Here are the log files.
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/9024372/eddi_issue.zip)

**Comment by SupremeAnu** [comment] 2022-07-01 01:31
This is an ongoing problem. I have closed all other applications accessing APIs to try to solve this.
Also, I am not using VoiceAttack. Just the TTS voices.

**Comment by Tkael** [comment] 2022-07-01 04:22
Assuming that `eddi1.log` represents a session where a crash occurred, I'm afraid that EDDI didn't capture any actionable data. The log just... ends. This may occur if the exception occurred inside of a system process rather than directly in EDDI.

Would you please check your system event log for system-level `Error` events which may correlate with EDDI crashing? There's a short tutorial [here](https://communities.bentley.com/products/utility_network_analysis___design/w/utility_network_analysis_and_design_wiki/33310/diagnose-a-program-crash-using-event-viewer) on how to do this.

**Comment by SupremeAnu** [comment] 2022-07-01 05:15
Okay, here are my EV logs.

`Application: EDDI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Speech.Synthesis.TtsEngine.ITtsEngine.Speak(System.Speech.Synthesis.TtsEngine.SPEAKFLAGS, System.Guid ByRef, IntPtr, IntPtr, IntPtr)
   at System.Speech.Internal.Synthesis.TtsProxySapi.Speak(System.Collections.Generic.List`1<System.Speech.Synthesis.TtsEngine.TextFragment>, Byte[])
   at System.Speech.Internal.Synthesis.VoiceSynthesis.SpeakText(System.Speech.Internal.Synthesis.SpeakInfo, System.Speech.Synthesis.Prompt, System.Collections.Generic.List`1<System.Speech.Internal.Synthesis.LexiconEntry>)
   at System.Speech.Internal.Synthesis.VoiceSynthesis.ThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()`
   
   `Faulting application name: EDDI.exe, version: 1.0.0.0, time stamp: 0x611fdac4
Faulting module name: MSVCR80.dll, version: 8.0.50727.9672, time stamp: 0x5db2b1b8
Exception code: 0xc0000005
Fault offset: 0x000149d1
Faulting process id: 0x4028
Faulting application start time: 0x01d88cff11685d66
Faulting application path: C:\Program Files (x86)\VoiceAttack\Apps\EDDI\EDDI.exe
Faulting module path: C:\Windows\WinSxS\x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9672_none_d08f9da24428a513\MSVCR80.dll
Report Id: 14de5861-e842-46ca-827a-5579226eb112
Faulting package full name: 
Faulting package-relative application ID: `

`Fault bucket 1383071936853818264, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: EDDI.exe
P2: 1.0.0.0
P3: 611fdac4
P4: MSVCR80.dll
P5: 8.0.50727.9672
P6: 5db2b1b8
P7: c0000005
P8: 000149d1
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFE7B.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1D7.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E8.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER216.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_EDDI.exe_c555acaf2987d8c7866db33ba53b1a3b3080c7_07c6d304_57e2c3fa-aa33-4b0c-8df3-844fea81b187

Analysis symbol: 
Rechecking for solution: 0
Report Id: 14de5861-e842-46ca-827a-5579226eb112
Report Status: 268435456
Hashed bucket: 6b17c1048b3bf0d52331a89946fbbb98
Cab Guid: 0`

Sorry for the wall of text, I hope it helps 👍

**Comment by Tkael** [comment] 2022-07-01 06:33
Ok. We now know that the problem is occurring when EDDI tries to access Windows system files dealing with speech synthesis.

Let's make sure that your system files don't have any issues. Please follow the guide [here](https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e) to check for and fix any system file issues?

**Comment by SupremeAnu** [comment] 2022-07-02 19:15
[CBS.log](https://github.com/EDCD/EDDI/files/9033495/CBS.log)
Here are my CBS logs. I have tested the issue and I don't seem to be having any issues with a crash atm. I will let you know if the issue occurs again. Thank you so much for your help and hard work!

**Comment by SupremeAnu** [comment] 2022-07-02 19:47
It has force closed again. T_T

**Comment by SupremeAnu** [comment] 2022-07-02 23:48
I'm running Odyssey version 4.0.0.1302

**Comment by Tkael** [comment] 2022-07-03 02:16
Which Windows version are you using? Is there any other application which may be accessing the system speech synthesizer? Did your system find and repair any issues related to `MSVCR80.dll`?

**Comment by SupremeAnu** [comment] 2022-07-05 01:56
I'm using Windows 10 version 21H1. And I did run the steps you recommended, it did find and repair corrupted files. I am using Discord only. I think I have Cortana disabled, I can't think of any other programs that would use the synthesizer.

**Comment by Tkael** [comment] 2022-07-05 06:05
Ultimately, this is looking like a system issue rather than an EDDI issue, but you might try reinstalling the C++ package as described [here](https://www.lifewire.com/how-to-fix-msvcr80-dll-not-found-or-missing-errors-2623805)?

**Comment by SupremeAnu** [comment] 2022-07-09 20:57
Hello, I have followed the steps you have sent above. I reinstalled VC and removed old registry entries. I also enabled the phonetic setting in EDDI to help with crash issues and haven't had a crash since. Thank you for your help!

**Comment by Tkael** [comment] 2022-07-09 21:13
Excellent. Closing as resolved. :-)

**Closed as completed by Tkael** 2022-07-09 21:13 UTC
