### ISSUE TITLE
Version 3.3.2 download failed

### ISSUE THREAD

**Issue by Stompmaster** [EDCD/EDDI#1037] opened 2018-12-24 08:02 UTC
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by benjaminjacobreji** [comment] 2018-12-24 10:53
Hi @Stompmaster 
I couldn't reproduce your issue. Could you be more specific
I downloaded the 4 files on the release page and they are successfully completed. I did try on 2 computers and my mobile. No errors in downloading. 

The 4 files are 
    EDDI-3.3.2.exe
    PDBs.zip
    Source code (zip)
    Source code (tar.gz)

It would be helpful if you could be specific with you issue or even how to reproduce it.
Thank you

**Comment by Tkael** [comment] 2018-12-24 16:05
Closing for lack of specificity.

**Closed by Tkael** 2018-12-24 16:05 UTC
