### ISSUE TITLE
Cannot connect to Frontier API

### ISSUE THREAD

**Issue by amirlx** [EDCD/EDDI#1788] opened 2020-05-26 10:34 UTC
## EDDI version in which issue is found
3.5.3-b1

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. Elite: Dangerous is already running
2. Run EDDI
3. Attempt to connect to Frontier Server
4. Authenticate Frontier login
5. Frontier returns: Open EDDI? 
![image](https://user-images.githubusercontent.com/34425057/82890144-b94c3700-9f19-11ea-9da4-f12d8f6174b0.png)

6. Click Open EDDI
7. Error message returned:

![image](https://user-images.githubusercontent.com/34425057/82890518-514a2080-9f1a-11ea-9f08-cd1f5c0d384a.png)

## Expected
Connect seamlessly to Frontier API

## Observed
Unable to connect to Frontier.

## Investigation
Tried Steam link with same effect.  Tried closing EDDI first then authenticating; Fronter does not respond at all.

**Comment by Tkael** [comment] 2020-05-26 12:14
Duplicate of #1786. We're aware of the issue and investigating.

**Closed as completed by Tkael** 2020-05-26 12:14 UTC
