### ISSUE TITLE
using ver 3.0.0-rc1 when i ran the program the first time i got all the tabs to set it up but  when i started it for the second time i only have 4 tabs showing "eddi , commander details , frontier api and text to spech" i dont get any coice in elite at all and obviously i cannot go back into setup to check anything as i do not have those tabs any more, i have uninstalled and reinstalled the program twice but i get the same thing I an running Win10 64bit if it helps , thanks neil

### ISSUE THREAD

**Issue by grondar** [EDCD/EDDI#452] opened 2018-04-02 07:35 UTC
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment] 2018-04-02 17:10
It sounds like a problem with your config or personality file is causing EDDI to not load completely. Please follow the steps in this link (https://github.com/EDCD/EDDI/blob/beta/TROUBLESHOOTING.md) to identify any issues with those files. 

Once you've done that, please report back. If the problem persists, please attach a copy of your log for review.

**Comment by Tkael** [comment] 2018-04-03 00:25
Looks like a duplicate of #442. I'll close this issue as a duplicate, but I'm still subscribed and you'll still be able to reply. 
Next time, a more succinct title for the bug report would be helpful. ;-)

**Closed by Tkael** 2018-04-03 00:25 UTC
Labels: duplicate

**Comment by grondar** [comment] 2018-04-04 20:25
Sorry none of the trouble shooting tips seem to help where can I find my log file? , I can find the eddi folder in c/users/myname/appdata but all that is in the eddi folder is a user config
Thanks
neil

Sent from Mail for Windows 10

**Comment by Tkael** [comment] 2018-04-05 08:05
One of your config files may be corrupt, or if you remove the config files and new config files don't reappear when you run EDDI then there may be a folder permissions route that is preventing EDDI from writing to that location.
EDDI.log should be appearing in the %appdata%/EDDI folder.
