### ISSUE TITLE
EDDI No Pad Location statement

### ISSUE THREAD

**Issue by dalvon** [EDCD/EDDI#254] opened 2017-11-23 23:00 UTC
EDDI no longer reports the location of the Pad upon approach. 
Reinstalled. Updated. 
Ensured all triggers are active. 
Ensured all plug-ins checked. 
Running VA in conjunction, no issues prior to last update.

**Comment by Tkael** [comment] 2017-11-25 18:14
Which station and system? If the server doesn't include the particular station that you docked at, that may have had an effect.

**Comment by Tkael** [comment] 2017-11-29 04:01
Closed as a suspected duplicate of #97. Please let us know if you have any more information about where this was observed.

**Closed by Tkael** 2017-11-29 04:01 UTC
