### ISSUE TITLE
EDDI v2.4.5 - Reporting limpets on board and no limpet controller when limpet controller is on board

### ISSUE THREAD

**Issue by DizzyBHigh** [EDCD/EDDI#420] opened 2018-03-14 09:21 UTC
## EDDI version in which issue found
EDDI v2.4.5

## Steps to reproduce

1. Launch with limpet controller and limpets on board
2. Speech responder says "You have limpets on board but no limpet controller"
3. Check mark for "check for the presence/absence of limpets and limpet controllers" cannot be unchecked.

## Expected
I expect it to say nothing if I have limpet controller and limpets on board
If i click the check mark for "check for the presence/absence of limpets and limpet controllers" i expect it to toggle on/off

## Observed
Check mark remains in place when clicked

## Investigation
NONE

**Comment by Tkael** [comment] 2018-03-14 12:07
Duplicate of #52. We're already looking into this.

**Closed** 2018-03-15 00:05 UTC
Labels: duplicate
