### ISSUE TITLE
Incorrect type of ship model in the ship monitor tab

### ISSUE THREAD

**Issue by Pryss** [EDCD/EDDI#318] opened 2017-12-27 21:51 UTC
I have sold my python and bought an anaconda.

In the Ship monitor tab, all informations, exept the Model of the ship are good. The ship model is stuck to Python.

**Comment by Tkael** [comment] 2017-12-28 00:02
This may be related to #305. If so, the cause should be fixed by the next release.

**Comment by Tkael** [comment] 2018-01-04 03:03
Closing as a duplicate of #305.

**Closed by Tkael** 2018-01-04 03:03 UTC
