### ISSUE TITLE
Easy to find keyboard shortcut to immediately silence EDDI text to speech add on

### ISSUE THREAD

**Issue by shodanx2** [EDCD/EDDI#2339] opened 2022-04-09 06:14 UTC
I imagine most users have no choice but to permanently disable all text to speech function

A "shut up immediately" button would allow text-to-speech to remain usable.

**Comment by Darkcyde13** [comment] 2022-04-09 11:15
You can always set up VoiceAttack (assuming you use it) to run the 'shutup' command, and assign a keyboard key to it.  You can find information on this here: https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration#shutup

For a more permanent silencing, you can use 'disablespeechresponder' instead.  With the right VA command, you could use this as a toggle along with 'enablespeechresponder'.  Information on these commands are just below the 'shutup' one in the above link.

**Comment by Tkael** [comment] 2022-04-10 03:11
Thank you for the suggestion, you are not the first to request this (please see #197). Closing as a duplicate of an existing item. o7

**Closed as completed by Tkael** 2022-04-10 03:11 UTC
Labels: duplicate

**Comment by shodanx2** [comment] 2022-04-10 03:44
Thanks, if there's an issue with EDDI registering a hotkey, would it be possible to make a "shutup" hotkey with AutoIT ? I don't have voice attack

**Comment by Darkcyde13** [comment] 2022-04-10 11:33
There is a free 'trial' version of VoiceAttack.  It's only limited to one user profile, and 20 commands in that profile, but other than that, it's a fully functioning version.  If you only want it to make EDDI shutup, you can easily use the free version to do that.

**Comment by Darkcyde13** [comment] 2022-04-10 11:44
I've had a (very) quick look at AutoIT.  You might possibly be able to do it with that I guess.  From what I can tell after only a cursory glance over it (so I may be way off here), you would have to have EDDI open on a second screen, and get AutoIT to use your mouse to select the Speech responder tab, and then click the Plugin enabled check box to deactivate the plugin.  However, I don't know how well that would stop any speech that's in progress, if it would at all.

I would say that the free version of VoiceAttack would easily be the best way to go for you.
