### ISSUE TITLE
unable to verify hanger status

### ISSUE THREAD

**Issue by Timnus** [EDCD/EDDI#1716] opened 2020-03-05 15:19 UTC
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
not used

## Steps to reproduce
1. goto home station
2. enter station ship yard
3. retrieve one of your ships for use

## Expected
notification of ship stored and of ship retrieved.

## Observed
get ship name you selected and hear "unable to verify hanger status. please verify connection to the pilots database"

## Investigation
rebooting EDDI fixes it but only if game is running 1st. if you launch EDDI then game you get error.

**Comment by Tkael** [comment] 2020-03-05 16:00
Hangar status information is sourced from the Frontier API. Please check whether you have an active connection to the Frontier API.

**Comment by Tkael** [comment] 2020-03-06 22:57
Please report back and confirm that connecting to the Frontier API resolves the issue?

**Comment by Timnus** [comment] 2020-03-07 03:54
if i start it before starting the saved game then i keep gettin the verbal error. if i restart it while in station the error does not come up. the API as nothing to do with it. 

Have a Wonderful Day!!!
Timothy Deane 

    On Friday, March 6, 2020, 4:57:48 PM CST, Brian Wilson <notifications@github.com> wrote:  
 
 
Please report back and confirm that connecting to the Frontier API resolves the issue?

**Comment by Tkael** [comment] 2020-03-07 04:41
If you inspect the script, you'll see that the Frontier API is important. Are you logged in to the Frontier API?

**Comment by Timnus** [comment] 2020-03-07 05:04
i set that when i started the application for the 1st time

Have a Wonderful Day!!!
Timothy Deane 

    On Friday, March 6, 2020, 10:41:13 PM CST, Brian Wilson <notifications@github.com> wrote:  
 
 
If you inspect the script, you'll see that the Frontier API is important. Are you logged in to the Frontier API?

**Comment by Tkael** [comment] 2020-03-07 05:18
Are you still logged in? The cookie can expire...

**Comment by Timnus** [comment] 2020-03-07 06:12
yes

Have a Wonderful Day!!!
Timothy Deane 

    On Friday, March 6, 2020, 11:18:41 PM CST, Brian Wilson <notifications@github.com> wrote:  
 
 
Are you still logged in? The cookie can expire...

**Comment by nepomuk16321** [comment] 2020-03-07 12:40
Hello Tkael, hello Timnus, 
I was just re-enacting your problem with me. 
* I flew into a station with a shipyard
* maneuvered to the shipyard in the station menu
* I ordered a ship from another station. 
Worked out fine. I'm using EDDI version 3.5.2. First I started EDDI then ELITE. 
In EDDI I controled the API connection. Then the actions (flight etc.) are executed.

Greetings nepomuk

**Comment by Timnus** [comment] 2020-03-08 06:42
> 
> 
> Hello Tkael, hello Timnus,
> I was just re-enacting your problem with me.
> 
>     * I flew into a station with a shipyard
> 
>     * maneuvered to the shipyard in the station menu
> 
>     * I ordered a ship from another station.
> 
> 
> Worked out fine. I'm using EDDI version 3.5.2. First I started EDDI then ELITE.
> In EDDI I controled the API connection. Then the actions (flight etc.) are executed.
> 
> Greetings nepomuk

how did you control that connection?
i just switched ships in same station.

**Comment by nepomuk16321** [comment] 2020-03-09 21:28
On the first tab "EDDI" you will find "EDDI Status:" at the bottom. Is that what you mean?

![image](https://user-images.githubusercontent.com/20616775/76259174-5968bd00-6255-11ea-9966-da55d2226d97.png)

**Comment by Timnus** [comment] 2020-03-10 11:38
when you exchange a ship in your hanger you hear about your hanger status. ikeep hearing the voice saying "unable to verify hanger status." unless i reboot while i am in the hanger. EDDI status always shows operational. 

Have a Wonderful Day!!!
Timothy Deane 

    On Monday, March 9, 2020, 4:29:00 PM CDT, nepomuk16321 <notifications@github.com> wrote:  
 
 
On the first tab "EDDI" you will find "EDDI Status:" at the bottom. Is that what you mean?

**Comment by nepomuk16321** [comment] 2020-03-10 20:02
Hello, Timnus,
Sorry, I tested it again. It works for me. So, it's not so easy for me to solve the problem now. 
I'll give it a try.
There is no direct hangar query ! EDDI responds to the event/script "Ship loadout" and/or 
"Market information updated.
Please compare here https://elite-journal.readthedocs.io/en/latest/Startup/#loadout
**Loadout
When written: at startup, when loading from main menu, or when _switching ships_, or after changing the ship in outfitting, or when docking SRV back in mothership.**
Now the content of the script "Ship loadout" is important. In the script a new function could now be called, e.g. "Hangar check". That's the way it is with me, for example. The content of the scripts depends on the used character. In the original character "EDDI" the hangar status is not queried. The script "Ship loadout" is empty. Which character do you use? The script "Ship loadout" in this character should now be examined. But my English knowledge is too bad for that. I recommend to use the character of CMDR Darkcyde. You can find it in the ELITE-Forum at its signature. You had to be logged in.
https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/page-101#post-8298955
Sorry and good luck


Translated with www.DeepL.com/Translator (free version)

**Comment by Timnus** [comment] 2020-03-13 20:14
?? load out? 

Have a Wonderful Day!!!
Timothy Deane 

    On Tuesday, March 10, 2020, 3:03:06 PM CDT, nepomuk16321 <notifications@github.com> wrote:  
 
 
Hello, Timnus,
Sorry, I tested it again. It works for me. So, it's not so easy for me to solve the problem now.
I'll give it a try.
There is no direct hangar query ! EDDI responds to the event/script "Ship loadout" and/or
"Market information updated.
Please compare here https://elite-journal.readthedocs.io/en/latest/Startup/#loadout
Loadout
When written: at startup, when loading from main menu, or when switching ships, or after changing the ship in outfitting, or when docking SRV back in mothership.
Now the content of the script "Ship loadout" is important. In the script a new function could now be called, e.g. "Hangar check". That's the way it is with me, for example. The content of the scripts depends on the used character. In the original character "EDDI" the hangar status is not queried. The script "Ship loadout" is empty. Which character do you use? The script "Ship loadout" in this character should now be examined. But my English knowledge is too bad for that. I recommend to use the character of CMDR Darkcyde. You can find it in the ELITE-Forum at its signature. You had to be logged in.
https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/page-101#post-8298955
Sorry and good luck

Translated with www.DeepL.com/Translator (free version)

**Comment by nepomuk16321** [comment] 2020-03-14 13:30
Hello Timnus,
I don't think you know how EDDI works yet. Sorry. EDDI reacts on entries in the Journal.log 
(and API and others https://github.com/EDCD/EDDI#eddi-the-elite-dangerous-data-interface). 
An entry is for example the event "Loadout" or also "Location". Please refer to the 
online help of the journal https://elite-journal.readthedocs.io/en/latest/Startup/#loadout . 
There is no event "Hangar status". The current status of the hangar is displayed via "Loadout". 
The script "Hangar check " is called from another event. For me this is "Location" and/or 
"Ship loadout" depending on the EDDI character you use. In the original EDDI-character the script
"Hangar status" does not exist at all. Here only "Location" is used for the hangar status.

Greetings nepomuk 

Translated with www.DeepL.com/Translator (free version)

**Comment by Tkael** [comment] 2020-03-14 14:10
To be clear, "hangar status" is reported from the `Launchbay report` script in the default personality. The `Launchbay report` script is triggered / invoked from the `Ship swapped` event script. 

The `Launchbay report` script uses data from the Frontier API and is written to alert the user if it is unable to connect to the Frontier API.

**Comment by Tkael** [comment] 2020-03-14 14:13
Neither `Location` nor `Loadout` event scripts invoke the `Launchbay report` script in the default personality.

**Comment by nepomuk16321** [comment] 2020-03-14 14:22
Thanks for the correction.

**Comment by nepomuk16321** [comment] 2020-03-15 12:50
Question: The causal ED event is the "Shipyardswap" event from the journal ? Right?
https://elite-journal.readthedocs.io/en/latest/Station%20Services/#shipyardswap
![image](https://user-images.githubusercontent.com/20616775/76701719-d667bc80-66c3-11ea-847b-b33427c2de85.png)

**Comment by Tkael** [comment] 2020-03-15 20:44
Correct.

**Comment by Tkael** [comment] 2020-03-19 00:07
Closing as (probably) resolved. Please let us know if there are any additional questions.

**Comment by Timnus** [comment] 2020-03-19 06:18
still have same problem. no idea why. only thing fixes it is if i am active in game and reboot EDDI. if  i log to main and then go back into game, it starts up again.

**Comment by Tkael** [comment] 2020-03-19 09:08
Please take a screenshot of the Frontier API tab in EDDI's UI and share it here.

**Comment by Timnus** [comment] 2020-03-19 16:12
![EddiFrontier](https://user-images.githubusercontent.com/27913772/77088432-711d0f80-69d2-11ea-9a59-e9aaafb4c52e.JPG)

**Comment by Tkael** [comment] 2020-03-20 09:00
Huh, now I'm even more baffled. You seem to be the only person with this issue. There may still be an issue with your connection to the Frontier API. Have you tried resetting the connection and logging back in?

**Comment by Timnus** [comment] 2020-03-21 02:19
tired that. seem like only way to fix it is by rebooting EDDI

**Comment by clinkingdog** [comment] 2020-03-22 02:12
FWIW I am also having this issue. I re-logged in to the API yesterday, and EDDI reports "Connected" to Frontier API, but I still get the warning message when I switch ships.

I _think_ I'm only getting it intermittently, not every single time I switch ships. (And it definitely didn't happen when I bought a new ship earlier, rather than switching to one I already own.)

**Comment by nepomuk16321** [comment] 2020-03-24 13:24
There is the variable "capi_activ". This variable is queried in the script (capi_activ true or false). 
How EDDI queries the availability of the API, I cannot say. But this results in "true" or "false".
Maybe it helps to include a pause at the beginning, {Pause(2000)}.

**Comment by clinkingdog** [comment] 2020-03-25 05:41
Update: It was working fine today, the launchbay report didn't give any errors and was silent when I swapped to a ship with no launchbay, and gave the correct details when I swapped to a ship with an SRV hangar installed.

**Comment by Tkael** [comment] 2020-03-30 08:09
`capi_active` is not a method, adding a pause will not help. 

@Timnus The log you sent on for a different ticket at around the same time states:
```
2020-03-27T04:35:53 [Warning] CompanionAppService:GetResponse Failed to obtain response, error code ProtocolError 
2020-03-27T04:35:53 [Info] CompanionAppService:Profile Failed to contact API server 
```

My working theory is as follows:
- The Frontier API server was unavailable. This cause exceptions to be thrown internally and an instance of the CompanionAppService could not be initialized. Exceptions are caught internally and logged but no changes propogated to the UI because the thrown exceptions had already killed the instance.
- Since an instance of `CompanionAppService` was not available `capi_active` defaulted to false.

**Comment by clinkingdog** [comment] 2020-04-03 23:17
Can't speak for the OP obviously, but I only have a single account so that applies to my reproduction at least.

**Comment by Tkael** [comment] 2020-04-04 01:18
@clinkingdog Thanks for that feedback. 
A verbose debug log is still probably our best bet for tracking this down to its source and confirming my theory.

**Comment by clinkingdog** [comment] 2020-04-04 11:59
@Tkael Sure thing. I'll see if I can repro again this weekend with verbose logging turned on. (Is there a downside to having it turned on? Perhaps I'll just leave it on in perpetuity in case future issues are hard to reproduce.)

I assume that you wouldn't learn much from a log where it succeeds, but let me know if that would be useful too. Since it's intermittent I expect to get a few of those before getting a failure!

**Comment by richardbuckle** [comment] 2020-04-04 14:57
There are a couple of performance downsides to keeping verbose logging turned on: (1) it hits the filesystem much harder and (2) writes to the log cannot happen in parallel, which means that a lot of background operations that would normally execute in parallel end up blocked waiting for "the speaking conch".

So we tend to advise keeping verbose logging on only until the problem has been identified, and then turning it back off.

**Comment by Tkael** [comment] 2020-04-04 18:31
Yes, if the issue persists between sessions then the best case would be: 
- get EDDI into the bad state, 
- enable verbose logging, 
- restart EDDI and wait until EDDI's CPU usage settles down (so that it is fully loaded), - disable verbose logging, 
- close EDDI and zip up the verbose log.

**Comment by Tkael** [comment] 2020-04-28 04:07
@clinkingdog Any luck with reproducing this and capturing it in a verbose log?

**Comment by clinkingdog** [comment] 2020-04-28 12:34
@Tkael I'm afraid not - sorry, I've been away from Elite for a while. The last time I tried, the bug didn't occur!

**Comment by Tkael** [comment] 2020-05-22 02:46
Closing due to inability to reproduce the issue. There should be a new release coming out shortly - please re-test once that version is released!

**Closed by Tkael** 2020-05-22 02:46 UTC
Labels: 6. not up to spec, help wanted, need help to reproduce
