### ISSUE TITLE
Star Descriptions being repeated

### ISSUE THREAD

**Issue by jparryjr** [EDCD/EDDI#1112] opened 2019-01-21 07:12 UTC
## EDDI version in which issue found
Version 3.3.4-b1.  Running as plug-in to Voice Attack.

## Steps to reproduce
1. FSD Jump into system.
2. If system is previously unexplored, autoscan or honking will report the type and description of star.

## Expected
A single report on the type and description of the star.

## Observed
1. During the autoscan or honking, speechresponder will repeat the description, with variations, 3 times.

## Investigation
This appears to be related to issue #1041 as well.  Attached are the speechresponder and journal files with entries related to two jumps made to the Omega Sector LN-I a10-0 and Omega Sector TD-S b4-17 systems.

[speechresponder.txt](https://github.com/EDCD/EDDI/files/2777851/speechresponder.txt)
[Journal.190120233801.01.txt.log](https://github.com/EDCD/EDDI/files/2777852/Journal.190120233801.01.txt.log)

**Comment by Tkael** [comment] 2019-01-21 08:07
Duplicate of #1041. We appreciate the report, but please don't duplicate open tickets.

**Closed by Tkael** 2019-01-21 08:07 UTC
Labels: duplicate
