### ISSUE TITLE
EDDI seems to ignore ship swap and cannot update ship loadout

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2500] opened 2023-01-20 18:31 UTC
## What's Wrong (please be as specific as possible)
EDDI seems to ignore ship swap and cannot update ship loadout

### Expected
I have many checks for items installed to the ship, and it should report them installed correctly

### Observed
[Describe what actually happened. Feel free to add screenshots, link to videos, etc to help explain what happened]
It will not detect any of the installed items installed to the ship.

### Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. Each time I swap ship

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version:  EDDI 4.0.2
  * VoiceAttack Version: [if applicable] v.1.10.3 64bit
* Localization [if applicable]
  * EDDI's language: [or the operating system language if EDDI's language setting is "Automatic"] English
  * Voice: [Name and language] English Microsoft Zira
![Loadout check](https://user-images.githubusercontent.com/21980416/213778508-274e9aac-dc3a-4bd5-b1d2-d475e5181720.png)

**Comment by Tkael** [comment] 2023-01-20 23:36
This is an issue which has already been identified for 4.0.2 but which should be resolved in the next release (soon!).

**Comment by Tkael** [comment] 2023-01-22 08:43
Duplicate of #2482

**Closed as completed by Tkael** 2023-01-22 08:43 UTC
Labels: duplicate
