### ISSUE TITLE
EDDI is being recognized by antivirus as malwalre/virus

### ISSUE THREAD

**Issue by carlostib** [EDCD/EDDI#1473] opened 2019-09-07 00:45 UTC
## EDDI version in which issue is found
3.4.3

## Steps to reproduce
1. Starting Upgrade
2. Antivirus recognize EDDI 3.4.3 as containing malware  Heur.AdvML.B 

## Expected
To upgrade EDDI to 3.4.3

## Observed
Antivirus recognize EDDI 3.4.3 as containing malware  Heur.AdvML.B 

## Investigation
This didn't happen before with EDDI until the latest 2 versions.

**Comment by Hoodathunk** [comment] 2019-09-07 01:17
You’re not the first. We don’t know why Norton/etc has decided to report as infected, but we’ve verified that it’s fine.

**Comment by Tkael** [comment] 2019-09-07 05:24
While we appreciate the alert, we're closing this as an unactionable duplicate of #1460.

**Closed by Tkael** 2019-09-07 05:24 UTC
