### ISSUE TITLE
EDDI started crashing it self and the VA yesterday. Reason unknown

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#1398] opened 2019-07-15 09:43 UTC
## EDDI version in which issue is found
3.4.1

## VoiceAttack version in which issue is found (as applicable)
1.7.6

## Steps to reproduce
If the VA has plugin support on EDDI will crash it in around a minute 

## Expected
Working fine as it has been since last update.

## Observed
Sunday afternoon something went wrong and the problem has continued since that. EDDI had trouble updating the events and started to lagg a lot already during the morning. After restarting PC in the afternoon, the crashing started. The only way i can keep the VA not crashing is to set the plugin support disabled

## Investigation
I suspect the latest Windows update had messed up something. I also rechecked all my audio devices and actually disabled everything but the basic mic in and stereo out defaults. So many things done it's hard to remember everything... (virtually been in panic since sunday lol). Reinstalled both EDDI and VA. Cleaned PC with every possible way including browsers cache etc... EDDI json too.

Frontier API refuses to connect and keeps ranting 'cannot run two instances at the same time' -EDDI will crash every single time on it's own, even without touching it. Maybe it's just my PC starting to die, but everything else runs smoothly and no crashing with other software.

EDIT: My best guess is currently that the Windows speech recognition engine is somewhow corrupt.
EDITEDIT: Oki i tried again to reinstall EDDI 3.4.1 Deleted all fiels except personalities from the appdata file and added them one at a time back in. EDDI did not crash, but could not connect to the Frontier API. Ohh and now as i type this VA just crashed... No plugin support enabled. This is weird.

**Comment by FireSammy** [comment] 2019-07-15 15:45
Tested VA & EDDI combo at my studio computer and so far no problems. It must be my home PC then :/
Will update things here if i can figure out whatta **** is the matter with that machine...

**Comment by FireSammy** [comment] 2019-07-15 17:52
[DxDiag 15.7.2019.txt](https://github.com/EDCD/EDDI/files/3393517/DxDiag.15.7.2019.txt)

**Comment by Tkael** [comment] 2019-07-16 00:46
It's possible that EDDI is hitting an exception while loading a journal event from your last game session.
 
Without EDDI or VA running, try 
1. starting Elite Dangerous, 
2. logging in, and then 
3. logging out. 
That'll create a new clean player journal entry for EDDI to load when you fire it back up again afterwards.

If you could also share your log file from a session that crashed (from `%appdata%/EDDI`), that'll help us to diagnose the cause for the future. (we recently found and fixed a bug that could cause this sort of behavior, a look at your log would confirm whether it's the same bug or different).

**Comment by FireSammy** [comment] 2019-07-16 09:07
Oki did that and EDDI refreshed the commander details correctly. Also rebuild the whole PC index service during last night, switched off the VA cover of the darkness -skin, and rechecked all audio settings. Double cleaned everything with resterts and nothing seems to be crashing now. Only thing remaining is that EDDI still claims cannot connect to Frontier API because of two instances running. VA is closed and browser is clean.

I vaguely recall there was possible to open the frontier browser login service (the one which pops up to connect EDDI) and manually delete the EDDI login thingy from there, but i don't remember how to do that? I recall it helped once but that was a long time ago.

[eddi.log](https://github.com/EDCD/EDDI/files/3396237/eddi.log)

**Comment by Tkael** [comment] 2019-07-17 00:07
Try the following:
1. Go to https://auth.frontierstore.net/ and log in.
2. Go to the "Authorized Applications" screen and deauthorize EDDI.
3. Now you should be able to re-authorize EDDI from its "Frontier API" tab.

Closing as resolved. :-)

**Closed by Tkael** 2019-07-17 00:07 UTC
Labels: 3. crash / lockup
