### ISSUE TITLE
System Report swaps orbital stations and planetary bases. 

### ISSUE THREAD

**Issue by PokerfaceCactus** [EDCD/EDDI#2474] opened 2023-01-04 12:54 UTC
## What's Wrong (please be as specific as possible)
when entering a system the system report describing the local system appears to be swapping the numbers on the station types. 

### Expected
when entering a system the system report is to explain the current state of the system.

### Observed
In multiple occasions have I experienced it reporting for example 17 orbital stations and 2 ground bases even though in the given station there is only 2 orbital stations and a lot of surface outposts. 

### Steps to reproduce
run EDDI, jump to another system, wait for the system report.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 4.0.1
  * EDDI's language: English
  * Voice: Personality EDDI, TTS Voice MS Zira

### Investigation Notes
I've manaully checked the system report, and running the test command again, and comparing in-game data vs the output from the speech responser. comparing the output of the responder file with the actual in-game data shows enough tho. 

I've noticed this happening a few times before 

the actual line as per speechresponder.out:
"Sinann is a poorly secured independent Democracy home to around 43 and a half thousand people, and is within the influence of Yuri Grom. Pixel Bandits Security Force is the immediate power. There are 17 orbital stations and 2 planetary stations in this system."
![Screenshot_4](https://user-images.githubusercontent.com/6827369/210555276-b411f53d-07c7-4f40-adda-0e9952a4f182.png)

### EDDI Logs
[eddi.log](https://github.com/EDCD/EDDI/files/10344198/eddi.log)

### Player journals
[Sinann Journal Data.txt](https://github.com/EDCD/EDDI/files/10344184/Sinann.Journal.Data.txt)

**Comment by Darkcyde13** [comment] 2023-01-05 13:58
This was a known issue in v4.0.1, which I believe is fixed in v4.0.2, although I can't find anything about it in the change logs.   Give the release candidate 1 (rc1) version a try [here](https://github.com/EDCD/EDDI/releases/tag/Release%2F4.0.2-rc1).  I'm pretty sure it's working OK for me on rc1.

**Comment by Tkael** [comment] 2023-01-06 07:18
I think @Darkcyde13 is probably correct. Ref. #2250.
Please let me know if the issue is still present in version rc1?

**Closed as completed by Tkael** 2023-01-06 07:18 UTC
