### ISSUE TITLE
EDDI Not detecting Two separate commander accounts

### ISSUE THREAD

**Issue by OddyB** [EDCD/EDDI#1699] opened 2020-02-04 13:39 UTC
## EDDI version in which issue is found
[ver 3.5.2]

I have a problem running two Steam version of Elite Dangerous. EDDI is report both accounts to EDSM and INARA to one account. This is showing inacurate details on the INARA & EDSM sites.

Even if playing one account without EDDI running it still up loads all the journals and does not detect they are for separate Commander accounts

[Describe what you expected to happen]
Each Commander data to be recognised and only send the data to INARA & EDSM for the Commander logins in EDDI

## Observed
EDDI reporting ships, materials, journeys to the wrong Commander acount

**Comment by Tkael** [comment] 2020-02-04 13:56
Duplicate of #505.

**Closed** 2020-02-04 13:56 UTC

**Comment by Tkael** [comment] 2020-02-04 14:00
Configuration settings are currently saved per your Windows account. Since EDDI does not currently support multiple commanders, the best option for using EDDI with multiple accounts is to use separate Windows accounts for each commander account.
