### ISSUE TITLE
Could state persistence between EDDI sessions be implemented

### ISSUE THREAD

**Issue by TribbleTrouble** [EDCD/EDDI#2206] opened 2021-06-21 17:29 UTC
## What happens now
It would be nice to remember setting from the last session so that they could be restored the next time I start up EDDI.

## What I'd like to happen 
Have a facility to store values to a file and the read them back again. This would be useful for remembering the context between games.

## How it can happen
Don't know enough about Cottle / EDDI to suggest an idea :)

## EDDI Version
4.0.0

**Comment by Darkcyde13** [comment] 2021-06-21 18:30
Do you use Voice Attack at all?  I started to use VA specifically to save data between gaming sessions.  It can read & write any data and variables to files, which can then be reloaded on start up.  I used this extensively when I first started saving my missions, crime, and cargo data before EDDI did it natively.

Well, it's just a thought. ;)

**Comment by Tkael** [comment] 2021-06-21 22:50
Which "state settings" are you asking about please?
Variables set with Cottle's native `set` command are not persistent by design. 
Do you mean the values of variables set with `SetState()`?

**Comment by TribbleTrouble** [comment] 2021-06-22 06:36
I was thinking about custom settings e.g. bodies landed on in system. @Darkcyde13 suggestion looks good though. I'll try that.

**Comment by Tkael** [comment] 2021-06-23 00:53
Closing as resolved for the time being with Darkcyde's suggestion.

**Closed as completed by Tkael** 2021-06-23 00:53 UTC
