### ISSUE TITLE
Voice assistant giving wrong body summary and body materials reports (in Ukrainian) - delimiters issue?

### ISSUE THREAD

**Issue by eilaattwood** [EDCD/EDDI#2035] opened 2020-12-11 00:18 UTC
## EDDI version in which issue is found
3.7.1

## VoiceAttack version in which issue is found (as applicable)
None

## Steps to reproduce
With default EDDI personality, perform Full System scan on the planed with unusual radius and a planet with high content of any material

## Expected
Voice assistant saying planet radius correctly, and giving correct material report without skipping data.

## Observed
Instead, e.g., "planet radius eleven thousand kilometers" assistant is saying "eleven kilometers".
When giving material report, voice assistant is skipping actual material names, by saying "body has high levels of ... and ..."

## Investigation
None

**Comment by Tkael** [comment] 2020-12-11 03:13
Are you using the default personality? If not, you might be using obsolete versions of some scripts.
Please temporarily swap to the default personality and verify whether the default scripts resolve the issue?

**Comment by eilaattwood** [comment] 2020-12-11 21:20
> 
> 
> Are you using the default personality? If not, you might be using obsolete versions of some scripts.
> Please temporarily swap to the default personality and verify whether the default scripts resolve the issue?

Yes, the default one. I've said that in the report.

**Comment by Tkael** [comment] 2020-12-12 08:11
Sorry, I was reading and responding on mobile. I missed that you stated that the scripts were from the default personality.

I asked whether you were using the default personality because what you're describing could quite easily be explained by customized scripts and your observations do not match my own recent observations. 

### 1. Planet radius (ref. `Body report summary` script)

Example journal event (note that the player journal reports radius in meters but the in-game UI uses kilometers - we report radius in kilometers):
```json
{ "timestamp":"2020-12-12T07:49:50Z", "event":"Scan", "ScanType":"Detailed", "BodyName":"HR 4906 A 3 a", "BodyID":7, "Parents":[ {"Planet":6}, {"Star":1}, {"Null":0} ], "StarSystem":"HR 4906", "SystemAddress":677934540337, "DistanceFromArrivalLS":898.461265, "TidalLock":true, "TerraformState":"", "PlanetClass":"Rocky body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"", "MassEM":0.152785, "Radius":3584120.000000, "SurfaceGravity":4.740503, "SurfaceTemperature":727.596252, "SurfacePressure":0.000000, "Landable":true, "Materials":[ { "Name":"iron", "Percent":20.530975 }, { "Name":"sulphur", "Percent":18.182728 }, { "Name":"nickel", "Percent":15.528769 }, { "Name":"carbon", "Percent":15.289791 }, { "Name":"phosphorus", "Percent":9.788786 }, { "Name":"chromium", "Percent":9.233459 }, { "Name":"zinc", "Percent":5.579550 }, { "Name":"zirconium", "Percent":2.384069 }, { "Name":"cadmium", "Percent":1.594323 }, { "Name":"molybdenum", "Percent":1.340661 }, { "Name":"polonium", "Percent":0.546882 } ], "Composition":{ "Ice":0.000000, "Rock":0.858988, "Metal":0.141012 }, "SemiMajorAxis":1226167440.414429, "Eccentricity":0.000000, "OrbitalInclination":39.408644, "Periapsis":214.423738, "OrbitalPeriod":9745915.532112, "RotationPeriod":10157926.444290, "AxialTilt":-0.408052, "WasDiscovered":true, "WasMapped":false }
```

Yielded speech:
```
Moon A 3 a is remarkable, with an extremely high radius of around 3 and a half thousand kilometers, an incredibly high surface temperature of nearly 721 Kelvin, and an incredibly high gravity of 0.48 times Earth's.
```

In-game UI confirmed a radius of `3,584 KM`, matching EDDI's speech output. 

Conclusion: No fault found.

### 2. Material naming (ref. `Body materials report` script)

Example journal event: 
```json
{ "timestamp":"2020-11-29T06:40:56Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Aurgel B 1", "BodyID":7, "Parents":[ {"Star":4}, {"Null":2}, {"Null":1}, {"Null":0} ], "StarSystem":"Aurgel", "SystemAddress":13866167444913, "DistanceFromArrivalLS":8.275464, "TidalLock":true, "TerraformState":"", "PlanetClass":"Metal rich body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"major silicate vapour geysers volcanism", "MassEM":0.111868, "Radius":2479961.250000, "SurfaceGravity":7.249788, "SurfaceTemperature":1198.464111, "SurfacePressure":0.000000, "Landable":true, "Materials":[ { "Name":"iron", "Percent":39.329296 }, { "Name":"nickel", "Percent":29.747030 }, { "Name":"chromium", "Percent":17.687691 }, { "Name":"zirconium", "Percent":4.566942 }, { "Name":"niobium", "Percent":2.687948 }, { "Name":"ruthenium", "Percent":2.428835 }, { "Name":"arsenic", "Percent":1.834815 }, { "Name":"mercury", "Percent":1.717445 } ], "Composition":{ "Ice":0.000000, "Rock":0.000000, "Metal":1.000000 }, "SemiMajorAxis":270442306.995392, "Eccentricity":0.013152, "OrbitalInclination":63.689158, "Periapsis":115.392447, "OrbitalPeriod":8091.816545, "RotationPeriod":8091.831240, "AxialTilt":-0.016568, "WasDiscovered":true, "WasMapped":true }
```

Yielded speech:
```
Planet B 1 is notable, with an incredibly inclined orbit. This body contains high levels of Zirconium, Niobium, Ruthenium and Mercury.
```

Conclusion: No fault found

______________________________________________________________

If any scripts have been customized, a `Reset` button will be active in the UI which will allow you to return the script back to the default.

If custom scripts are not at fault, I'll need a little more information. Is this happening every time or did it happen just the once? If this occurred just the once, it would be helpful to have as much information as possible about the body in question (including a copy of the applicable player journal entry from your local storage if possible... these are saved to your [Saved Games] folder/Frontier Developments/Elite Dangerous and we'd need the file ending with .log from play session where the issue was observed).

**Comment by eilaattwood** [comment] 2020-12-12 09:16
I think, I have the idea why first one is failing for me. I have my game language set to Russian right now. And Russian locale has comma as a decimal separator, not the dot. I think, that messes things up.

Also, maybe variable also got localized material names? I thought they aren't localized. That may be a point, because English-speaking VAs can't pronounce russian (obviously).

I should set game language to English to test. However, decimal delimiter problem can be fixed by checking for the delimiter in the code, I guess.

**Comment by Tkael** [comment] 2020-12-12 13:32
Is your language setting set to `Automatic`? If so, we try to apply localization matching the language of you local operating system. Is that Russian? 

Are you using a Russian speaking Text-to-Speech voice or one from another language?

1. I wrote up a quick test for parsing the journal using a Russian localized thread vs. an English localized thread. The result seems to come out equal in both English and Russian. I don't think we can explain the numerical difference via the decimal separator issue. Furthermore, if the dot were being read as a thousands separator then I believe we would expect the number to be rendered larger rather than smaller in the Russian localization?

2. If you are using (for example) an English voice for Text-to-Speech but EDDI is localizing to Russian then that would be problematic. For best results, English voices should use English EDDI localization, Russian voices should use Russian EDDI localization, etc. I can confirm that EDDI does include cyrillic characters in the Russian translations for material names and that my English speaking TTS voice is silent when I try to render a word which uses the cyrillic alphabet.

**Comment by eilaattwood** [comment] 2020-12-12 14:41
Well, I'm Ukrainian myself, and my system locale is Ukrainian. But Elite has no Ukrainian translation, so I've set Elite language to Russian explicitly, as this is my secondary well-known language (English being the third :)).

I'm using English Text-To-Speech, because default EDDI personality script is written in English, using russian voice is messing it up.

Edit: Oh, yes, EDDI was also set to Russian. I've just switched it to English, and will test it soon.

**Comment by eilaattwood** [comment] 2020-12-12 22:30
I can confirm: after switching EDDI to English language all mentioned problems are gone, including the one with decimal delimiter. Elite locale was left at Russian, so only EDDI locale matters.

**Comment by Tkael** [comment] 2020-12-12 23:07
Yes, we don't have a Russian (or Ukrainian) translation of the default personality so I can see how that might mess things up. If you'd like to submit a translation then we can incorporate it, but otherwise it probably would be best to stick to English. 

I'll take another look at the quick tests I wrote last night and see if I can figure out the decimal delimiter issue.

**Comment by eilaattwood** [comment] 2020-12-13 11:59
Yeah, I can see two possible problems with the delimiter:

1. The game data source is yielding data in the 12,345 format, where comma is thousand delimiter. When Russian localization is applied, that comma is seen as decimal delimiter instead of thousand delimiter, turning 12,345 to 12.345 instead of 12345, then rounding it down to just 12

2. In Russian, whitespace is often used as thousands delimiter, so data source can yield something like 12 345, and string to int conversion can possibly truncate that to 12.

Maybe the solution would be just to get rid of that digit group delimiter? Just delete it from the number? It is not needed to interpret numbers correctly, after all. It just gets in the way...

This is how default numbers format settings looks like in my locale. Russian formats are the same.
![image](https://user-images.githubusercontent.com/28134842/102011420-987bef80-3d4c-11eb-8dd7-085296b9c30e.png)

**Comment by Tkael** [comment] 2020-12-13 13:20
I believe the file contents should be written in English and should use standard English delimiters but this is a good opportunity to test that. 

If you can provide a copy of a player journal file from `[your Saved Games folder]/Frontier Developments/Elite Dangerous/` then I inspect and run tests against that original game data. Preferably, we'd want a recent player journal from a play session where you were scanning bodies.

**Comment by eilaattwood** [comment] 2020-12-14 00:09
Here it is.
[Journal.201213193305.01.log](https://github.com/EDCD/EDDI/files/5685812/Journal.201213193305.01.log)

**Comment by Tkael** [comment] 2020-12-14 01:01
Thanks. The file contents are written in English and use standard English delimiters. Here's a scan event from the file as an example:
```json
{ "timestamp":"2020-12-13T18:05:45Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Col 285 Sector LX-Q b19-5 A", "BodyID":1, "Parents":[ {"Null":0} ], "StarSystem":"Col 285 Sector LX-Q b19-5", "SystemAddress":11667681125825, "DistanceFromArrivalLS":0.000000, "StarType":"M", "Subclass":9, "StellarMass":0.199219, "Radius":233092672.000000, "AbsoluteMagnitude":11.549698, "Age_MY":11162, "SurfaceTemperature":2125.000000, "Luminosity":"VI", "SemiMajorAxis":21007056832313.539063, "Eccentricity":0.127396, "OrbitalInclination":-65.996054, "Periapsis":130.015923, "OrbitalPeriod":399133247137.069702, "RotationPeriod":134521.292843, "AxialTilt":0.000000, "WasDiscovered":true, "WasMapped":false }
```

**Comment by eilaattwood** [comment] 2020-12-14 19:46
So misconversion is happening somewhere in EDDI. Makes sense, because only EDDI locale setting changes it's behavior.

**Comment by Tkael** [comment] 2020-12-15 08:51
Agreed. Now to track it down...

**Comment by richardbuckle** [comment] 2020-12-18 01:09
Assigning myself because while I have only been studying Russian for about 9 months during lockdown, that does at least give me a basic understanding of the alphabet and the basic grammar.

I'm aware that Ukrainian and Belorussian are not the same as Russian, and even use different variants of the alphabet, but I am also learning that the basic grammar is very close.

**Comment by eilaattwood** [comment] 2020-12-19 21:18
> I'm aware that Ukrainian and Belorussian are not the same as Russian, and even use different variants of the alphabet, but I am also learning that the basic grammar is very close.

They are not, but alphabet differs in only a few letters, grammar is quite similar, and delimiter system is the same.

**Comment by richardbuckle** [comment] 2021-03-16 00:08
We are currently working on fixing this for our Russian translation and we are hopeful that the fix will also work for you.

**Comment by richardbuckle** [comment] 2021-03-16 00:09
Also, the fix will allow for proper declension of Slavic numerals (2-4 genitive singular, 5+ genitive plural, etc).

**Comment by Tkael** [comment] 2021-05-31 08:57
I believe this is now fixed.

**Closed as completed by Tkael** 2021-05-31 08:57 UTC
Labels: 6. not up to spec, localization
