### ISSUE TITLE
{TXT:Name} not work

### ISSUE THREAD

**Issue by hoksilato2** [EDCD/EDDI#997] opened 2018-12-12 19:09 UTC
## EDDI version in which issue found
3.1.2, 3.3-b1

## Steps to reproduce

Use this variable on VoiceAttack when games it's allready open.

## Expected
Shows commander Name

## Observed
With 3.1.2 EDDI version not work, with new 3.3-b1 either.

## Investigation
If I replace TXT:Name for TXT:Home System (for example), variables shows correctly the home system configured. But "Name" variable not works :(

**Comment by Tkael** [comment] 2018-12-12 21:10
Caused by the Frontier API going down hard, though you should also have this value written when you load into the game with EDDI running).

**Comment by Hoodathunk** [comment] 2018-12-12 22:05
Yup, should happen from CommanderContinued event.

```        private bool eventCommanderContinued(CommanderContinuedEvent theEvent)
        {
            // If we see this it means that we aren't in CQC
            inCQC = false;

            // Set our commander name
            if (Cmdr.name == null)
            {
                Cmdr.name = theEvent.commander;
            }

            return true;
        }

```

**Comment by Tkael** [comment] 2018-12-23 15:09
Closing since this is fixed by simply starting EDDI before Elite, or logging out and logging back in while EDDI is running.

**Closed by Tkael** 2018-12-23 15:09 UTC
