### ISSUE TITLE
Can't disable speech responders

### ISSUE THREAD

**Issue by jcdick1** [EDCD/EDDI#2075] opened 2021-01-12 05:28 UTC
## What's Wrong (please be as specific as possible)
Having created some event responses in VA directly, I'd like to disable some of the speech responders in EDDI.  However, I can't uncheck the "enabled" box on any of the responders.

### Expected
The checkbox to be cleared and that part of the speech responder to not run

### Observed
The checkbox in the "Enabled" column doesn't clear

### Steps to reproduce
1. Select the "Speech Responder" tab
2. Select any of the responders
3. Click on its respective checkbox in the "Enabled" column
4. Checkbox doesn't clear

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: 3.7.1
  * VoiceAttack Version: [if applicable] 1.8.7
* Localization [if applicable]
  * EDDI's language: US English
  * Voice: Ivona Gwyneth

## My Investigation
I've looked through the Wiki to see if maybe there was something less intuitive than just clicking the box I need to do to disable a speech responder, but didn't see anything.  I've tried running EDDI standalone, in case having it as a plugin to VA somehow "locked" the speech responders.

**Comment by Tkael** [comment] 2021-01-12 05:58
This is by design.

The Speech Responder contains both "Event-based scripts" and "Non-event-based scripts". Only scripts directly triggered by an event can be disabled. It sounds like you are trying to disable a script which isn't directly triggered by any event (though it still may be invoked by another script).

Event-based scripts can be disabled but cannot be deleted. They can also be assigned to differing priorities, as noted below:

1 - high priority, interrupts other speech 
2 - high priority 
3 - default priority 
4 - low priority 
5 - low priority, interruptible by any higher priority speech 

Non-event-based scripts must be invoked, either by using a function call from another script or via the VoiceAttack plugin. Since they must be invoked they can be deleted but can neither be disabled nor assigned to new priorities. If invoked by another script, they will take on the priority of the invoking script. If invoked from VoiceAttack, they will use the default priority unless a new priority is assigned via the VoiceAttack plugin, as documented in https://github.com/EDCD/EDDI/wiki/VoiceAttack-Integration.

**Closed as completed by Tkael** 2021-01-12 05:58 UTC

**Comment by jcdick1** [comment] 2021-01-12 06:13
But I can't uncheck _any_ of the speech responders on that page. Not a single check mark in the entire column will clear.  I've gone down the entire page, clicking on each speech responder.

**Comment by Tkael** [comment] 2021-01-12 06:17
Have you created a copy of the default personality? The default personality is not editable (and that includes enabling and disabling scripts).

**Comment by jcdick1** [comment] 2021-01-12 06:26
Ah.  There's the "less than intuitive" step that I was missing.  As "enabling" and "disabling" isn't really editing, I saw no reason to make a copy.  And the speech responder page itself says that they can be enabled/disabled and reprioritized, but not "only if you are using a _copy_ of the default personality."  I'll make a note in my VA/EDDI docs about that so I don't make the mistake in the future.  Thank you for clearing it up!
