### ISSUE TITLE
EDDI Crashing on launch

### ISSUE THREAD

**Issue by randyDarsh** [EDCD/EDDI#1249] opened 2019-03-17 17:52 UTC
## Version
3.3.6 stand alone

## Steps to reproduce
Launching EDDI v3.3.6 causes it to crash.

## Expected
Not to crash and open

## Observed
Crashing when open

## Investigation
Check the windows error logs, and saw these two errors being logged (in chronological order)

ERROR 1: 
Application: EDDI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(System.String)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.XmlReader.IsStartElement(System.String, System.String)
   at System.ServiceModel.Syndication.Atom10FeedFormatter.CanRead(System.Xml.XmlReader)
   at System.ServiceModel.Syndication.SyndicationFeed.Load[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Xml.XmlReader)
   at SimpleFeedReader.FeedReader.RetrieveFeed(System.String, SimpleFeedReader.IFeedItemNormalizer)
   at GalnetMonitor.GalnetMonitor.<monitor>g__monitorGalnet|16_0()
   at GalnetMonitor.GalnetMonitor.monitor()
   at GalnetMonitor.GalnetMonitor.Start()
   at Eddi.EDDI+<>c__DisplayClass119_0.<keepAlive>b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

ERROR 2: 
Faulting application name: EDDI.exe, version: 1.0.0.0, time stamp: 0x5c6642b2
Faulting module name: KERNELBASE.dll, version: 10.0.17134.556, time stamp: 0xadca2670
Exception code: 0xe0434352
Fault offset: 0x001118a2
Faulting process id: 0x3240
Faulting application start time: 0x01d4dce8ce0aa586
Faulting application path: p:\Program Files (x86)\VoiceAttack\Apps\EDDI\EDDI.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6c8c10d2-a43c-402b-bc79-4db2f6c31d8b
Faulting package full name: 
Faulting package-relative application ID:

**Comment by randyDarsh** [comment] 2019-03-17 18:05
Downloaded and installed EDDI V3.3.7-b1 and the issue has gone away, but the main release 3.3.6 is still having the same issue as in my original post.

**Comment by Tkael** [comment] 2019-03-17 19:05
This is a known issue with 3.3.6, caused by FDev removing the Galnet RSS feed and EDDI not handling the missing feed gracefully. It is resolved in 3.3.6 by disabling the Galnet monitor.

**Closed by Tkael** 2019-03-17 19:05 UTC
