### ISSUE TITLE
Market Information Update not working

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#606] opened 2018-05-29 16:16 UTC
## EDDI version in which issue found
EDDI v3.0.1 beta 4 under Voice Attack

## Steps to reproduce
Land at any station, Market Information Update should read out some information.

## Expected
Market Information Update should read out what commodities are good to purchase, and also what commodities you can sell for a profit.

## Observed
Nothing is read out when the event script executes.

## Investigation
(The following is reproduced from FDev Forums, I'm now putting it in the correct place for a report)

With all my trading, I've only just noticed that I'm not getting any market information when I dock.  The Market information updated script does execute, but I'm getting nothing reported.

I've been transporting Resonating Separators to Iving Hub in Y Velorum, buying Gallium and taking it to Conway City in LTT 4961, then making the return trip with more Resonating Separators.

First I've found that ship.role in the Market information updated script isn't populated.  The role is set as default (multi-purpose) in my ship monitor, but I've tried swapping it to trading, and back to multipurpose, without any luck. As this is not set, Commodity Purchase Check isn't being called. Is this a bug, or am I doing something wrong?  Do I need to delete my shipmonitor.json?

Second, after a bit of testing, I've found that in the Commodity Sale Check script the marketcommodity.sellprice is always zero for all commodities at the station.  The buyprice is correct for everything though.

For example, I have 432 tonnes of Resonating Separators in my cargo hold.  I am at Irving Hub in Y Velorum.  On the market, I can sell these for a profit of 4,195 each (currently). Running the Commodity Sale Check script results in no output at all.  After checking that the script is matching the cargo item to a market item (it is, EDDBID is 69) I started checking other variables and quickly found that the sell prices are all zero.

I added this code into the market() function to check:-
```
{_ Function to find a given commodity in market}
{set market(commodity) to:
    {for marketcommodity in station.commodities:
[B][U]{marketcommodity.EDDBID}-{marketcommodity.name}-{marketcommodity.sellprice},[/U][/B]
        {if marketcommodity.EDDBID = commodity.EDDBID:
            {return marketcommodity}
        }
    }
}
```

And got this output:-
```
1-Explosives-0, 
2-Hydrogen Fuel-0, 
277-Hydrogen Peroxide-0, 
278-Liquid oxygen-0, 
3-Mineral Oil-0, 
118-Surface Stabilisers-0, 
271-Water-0, 
5-Clothing-0, 
6-Consumer Technology-0, 
7-Domestic Appliances-0, 
14-Animal Meat-0, 
15-Coffee-0, 
16-Fish-0, 
17-Food Cartridges-0, 
18-Fruit and Vegetables-0, 
19-Grain-0, 
20-Synthetic Meat-0, 
21-Tea-0, 
282-Insulating Membrane-0, 
22-Polymers-0, 
23-Semiconductors-0, 
24-Superconductors-0, 
28-Microbial Furnaces-0, 
29-Mineral Extractors-0, 
30-Power Generators-0, 
31-Water Purifiers-0, 
305-Advanced Medicines-0, 
33-Basic Medicines-0, 
35-Performance Enhancers-0, 
36-Progenitor Cells-0, 
37-Aluminium-0, 
38-Beryllium-0, 
39-Cobalt-0, 
40-Copper-0, 
41-Gallium-0, 
42-Gold-0, 
43-Indium-0, 
44-Lithium-0, 
45-Palladium-0, 
47-Silver-0, 
48-Tantalum-0, 
49-Titanium-0, 
50-Uranium-0, 
51-Bauxite-0, 
52-Bertrandite-0, 
53-Coltan-0, 
108-Cryolite-0, 
54-Gallite-0, 
107-Goslarite-0, 
55-Indite-0, 
56-Lepidolite-0, 
280-Lithium Hydroxide-0, 
276-Low Temperature Diamonds-0, 
281-Methane Clathrate-0, 
83-Painite-0, 
105-Pyrophyllite-0, 
57-Rutile-0, 
58-Uraninite-0, 
8-Beer-0, 
9-Liquor-0, 
12-Wine-0, 
84-Limpet-0, 
61-Advanced Catalysers-0, 
65-Bioreducing Lichen-0, 
67-H.E. Suits-0, 
69-Resonating Separators-0,
```

As you can see, Resonating Separators are right at the end and sellprice for everything is zero. When I run the same test using buyprice, I get the list with all the correct buying prices.

Any ideas?

**Comment by Tkael** [comment] 2018-05-30 06:38
Comparing to the latest records on ROSS from an EDMC user, it looks like perhaps EDDI didn't parse the commodities data from the Frontier API correctly? See https://ross.eddb.io/eddn/log/56250266

**Comment by Tkael** [comment] 2018-05-30 07:04
{ship.role} was broken by changes we made to definitions for internationalization. I'm going to submit a PR to restore it. 
It should be noted that we now are using "Multipurpose" rather than "Multi-purpose" as well.

**Comment by Darkcyde13** [comment] 2018-05-30 13:06
Thank you for the update. :)

**Comment by Tkael** [comment] 2018-06-07 02:56
Ship role fixed merged. The remainder may be dependent on the source data being incorrect, which would make it a duplicate of #97. Closing for now. :-)

**Closed by Tkael** 2018-06-07 02:56 UTC
Labels: 6. bug / not up to spec, PR submitted
