### ISSUE TITLE
Ship Monitor not recognising Imperial Cutter. No module or ship info available.

### ISSUE THREAD

**Issue by Darkcyde13** [EDCD/EDDI#87] opened 2017-09-18 23:43 UTC
I've finally managed to get back to my Cutter tonight to test this out.  When I am in my Cutter EDDI knows nothing about it and it does not appear in the ShipMonitor.

As per conversation with VerticalBlank, I have renamed 'shipmonitor.json' and restarted EDDI.  My AspX was immediately identified and entered into the ShipMonitor as soon as I loaded my game, but swapping to and from my Cutter results in no entry in ShipMonitor, no module info about it, and EDDI simply calling it 'your Cutter' all the time.

When fuel scooping, the ship.fueltanktotalcapacity variable is not set, resulting in being told my fuel was basically zero all the time.  I've tried a couple of other 'ship.<...>' variables and none of them seem to be set.

**Comment by Tkael** [comment] 2017-09-19 00:19
This is a duplicate of another issue (https://github.com/EDCD/EDDI/issues/37). Hoodathunk is investigating.

**Closed by Tkael** 2017-09-19 00:19 UTC
Labels: duplicate
