### ISSUE TITLE
Misnamed signal sources ("Combat Zone" should be "Conflict Zone")

### ISSUE THREAD

**Issue by eavdmeer** [EDCD/EDDI#2071] opened 2021-01-10 12:36 UTC
Signal sources are referred to as 'Combat Zone', while they are, in fact, 'Conflict Zone'.

In addition, reporting is awfully verbose. For a gas giant with a couple of RES sites and Conflict Zones, each one of them is reported individually with 'full honors'. It would be very helpful to at least provide the possibility to abbreviate some of them:

High Intensity Resource Extraction Site => High RES Site
Medium Intensity Resource Extraction Site => Medium RES Site
Low Intensity Resource Extraction Site => Low RES Site

This currently cannot be changed at all by the user because the `Signal detected` script does not allow the spoken terms to be changed, only to disable them completely. It would require a complete cottle lookup table to make changes.

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  * EDDI Version: v.3.7.1
  * VoiceAttack Version: v1.8.7
* Localization [if applicable]
  * EDDI's language: US/English
  * Voice: Microsoft David

**Comment by Darkcyde13** [comment] 2021-01-10 13:36
I believe that the Signal source script is triggered for each individual signal detected, because (I think) they are individual entries in the player Journal.

This also bugged me for a while, so I made changes to the script to fix it.  I have been able to mitigate the repeating of same items to some extent by adding code to prevent the same thing being repeated one after the other.  In this case only the first item will be mentioned and all subsequent ones will be ignored for 30 seconds.

I've added this code to the script just below the 'spokensources' section:
```
{if SecondsSince(state.eddi_context_arrivaltime) > 30:
    {SetState('eddi_context_last_signal', null)}
    {SetState('eddi_context_arrivaltime', SecondsSince(0))}
}
```

I've then added a check to this line (line 35 in the default script):
`    {if event.source && !event.stationsignal && event.scource != state.eddi_context_last_signal:`

And then right at the end of the script, I've added this SetState():
`{SetState('eddi_context_last_signal', event.source)}`

With these additions, the whole listing of signal sources is greatly reduced.  It's not 100% perfect, but does the job very well.  Each different type will be spoken at least once, so you'll never miss anything.  The only time you'll hear a repeat, is when you get a situation something like "High RES", "Medium RES", "High RES", but these don't seem to happen very often.  The 30 second limit means that you'll still hear everything when you find more signals, i.e. when getting close to another planet.

@Tkael & @richardbuckle  You are welcome to use these additions in the default script if you wish. :)

**Comment by Darkcyde13** [comment] 2021-01-10 15:56
I realised my previous reply was irrelevant, so I deleted it.

You could add some code to shorten things for yourself.  You could replace line 39 {event.source} with this:
```
        {if event.source = "High Intensity Resource Extraction Site":
            High RES Site
        |elif event.source = "Medium Intensity Resource Extraction Site":
            Medium RES Site
        |elif event.source = "Low Intensity Resource Extraction Site":
            Low RES Site
        |else:
            {event.source}
        }
```

You could expand this to include the combat zones too, which would also let you change them to report 'Conflict' instead of 'Combat'.

**Comment by Darkcyde13** [comment] 2021-01-10 16:52
Hmm, I've been running some tests with this and I think there may be a problem with the default script and the use of the 'event.unique' variable.  I'll open a new issue for it.

**Comment by Tkael** [comment] 2021-01-10 17:01
The `Signal detected` script is intended to only report unique signal sources but there is a bug in 3.7.1 which would sometimes cause the uniqueness property to fail. We've already addressed this in our version 3.7.2-rc1 release candidate (which we expect to promote very shortly as a full release).

**Comment by Tkael** [comment] 2021-01-10 17:04
Replacing spoken terms with ones which better match your preferences is certainly possible, as Darkcyde has already described.

**Comment by Darkcyde13** [comment] 2021-01-10 17:23
> The `Signal detected` script is intended to only report unique signal sources but there is a bug in 3.7.1 which would sometimes cause the uniqueness property to fail. We've already addressed this in our version 3.7.2-rc1 release candidate (which we expect to promote very shortly as a full release).

I've opened a new issue as this doesn't seem to be working as intended. #2072

**Comment by eavdmeer** [comment] 2021-01-10 18:08
> I realised my previous reply was irrelevant, so I deleted it.
> 
> You could add some code to shorten things for yourself. You could replace line 39 {event.source} with this:
> 
> ```
>         {if event.source = "High Intensity Resource Extraction Site":
>             High RES Site
>         |elif event.source = "Medium Intensity Resource Extraction Site":
>             Medium RES Site
>         |elif event.source = "Low Intensity Resource Extraction Site":
>             Low RES Site
>         |else:
>             {event.source}
>         }
> ```
> 
> You could expand this to include the combat zones too, which would also let you change them to report 'Conflict' instead of 'Combat'.

Granted, this is possible, but that's what I meant by 'translation table'. I've put something very similar to this in the script now.

Good to see that the repetition is unintended. If that's fixed, the annoyance level goes down significantly. Your workaround also looks very acceptable.

@Tkael: yes, I can now use my own preference. However, my point is that the things really are not called 'Combat Zone' in the game. Cornflakes Zone, anyone 🤣

**Comment by Tkael** [comment] 2021-01-10 19:05
I'm a little averse to changing these strings from "combat" to "conflict" since doing so would 
1. require re-translating the strings
2. require anyone with a customized `Signal detected` script to manually update their script for the new strings

With respect to #2072, Darkcyde and yourself were right to point out a problem. It'll be fixed in the 3.7.2 release.

**Comment by Darkcyde13** [comment] 2021-01-10 19:17
> yes, I can now use my own preference. However, my point is that the things really are not called 'Combat Zone' in the game. Cornflakes Zone, anyone 🤣

While they may not be called 'Combat Zone' in game, my guess is that they are called that in the Journal events, hence why they are listed as such in EDDI.  Unfortunately, I'm in Colonia at the moment, and there don't appear to be any conflict zones in the area to check out and confirm this.

**Comment by Tkael** [comment] 2021-01-10 19:24
Actually no.
```json
{ "timestamp":"2021-01-10T18:24:43Z", "event":"FSSSignalDiscovered", "SystemAddress":27076330676, "SignalName":"$Warzone_PointRace_High:#index=1;", "SignalName_Localised":"Conflict Zone [High Intensity]" }
{ "timestamp":"2021-01-10T18:24:43Z", "event":"FSSSignalDiscovered", "SystemAddress":27076330676, "SignalName":"$Warzone_PointRace_Med:#index=1;", "SignalName_Localised":"Conflict Zone [Medium Intensity]" }
{ "timestamp":"2021-01-10T18:24:43Z", "event":"FSSSignalDiscovered", "SystemAddress":27076330676, "SignalName":"$Warzone_PointRace_Low:#index=1;", "SignalName_Localised":"Conflict Zone [Low Intensity]" }
```

The journal does use `Conflict` rather than `Combat`. `Combat` was an inadvertant change while converting the output to a friendlier form for EDDI.

**Closed as completed** 2021-02-15 06:47 UTC
Labels: 8. annoyance
