### ISSUE TITLE
Log File Flooded With Errors

### ISSUE THREAD

**Issue by c0dejunKie** [EDCD/EDDI#846] opened 2018-09-16 19:21 UTC
## EDDI version in which issue found
[please give the full version number here, not just "latest" or "current", and also say whether you are running under Voice Attack or standalone]

VoiceAttack - v1.7.2
EDDI - v3.1.0-b1

## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

Just play elite normally.

## Expected
[describe what you expected to happen]

I expected the log file to be relatively free of errors, the odd error here and there is fine, but my log is literally showing thousands of errors since the update this morning to v3.1.0-b1

Also note that even with all the errors, EDDI and voice attack seem to be working with no problems, I just wanted to make sure that since I am having so many errors that EDDI is working properly and nothing is wrong.

## Observed
[describe what happened instead]

Too many errors to count, so I just uploaded my log file that starts from the point where EDDI was updated this morning to v3.1.0-b1.  Please note that most of these errors have shown up in the log many times before the v3.1.0-b1 update.
[eddi.log](https://github.com/EDCD/EDDI/files/2386901/eddi.log)

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

I know that the devs have already been informed about these 2 errors:

2018-09-16T16:00:18 [Info] Personality:fixPersonalityInfo Failed to find scriptsMissions;Passengers 

and 

2018-09-16T16:47:14 [Error] EDDI:conditionallyRefreshProfile Exception obtaining profile System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EddiCompanionAppService.CompanionAppService.OutfittingFromProfile(JObject json)
   at EddiCompanionAppService.CompanionAppService.Station(String systemName)
   at Eddi.EDDI.conditionallyRefreshProfile()

So I'll leave those errors to be looked at in the other posts that are already being looked into, but the rest of the errors that are in my log file need to be looked into.

Please let me know if there is any other information that I may be able to give to you to help look into these issues.  

Thank you very much.

**Comment by Darkcyde13** [comment] 2018-09-16 19:47
Hmm, I've tried your 'band aid' fix, but it doesn't work for me, I still get a log full of errors.
> 2018-09-16T19:42:17 [Info] Personality:fixPersonalityInfo Failed to find scriptsMissions;Passengers 

I've tried different variations of 'Mission' and 'Passengers', both plural and with/without a capital 'P', but I always get those errors in my log.

**Comment by c0dejunKie** [comment] 2018-09-16 20:12
hmmm strange, seems to stop showing the error in my log, wonder why not for you...  Are you using your own personality? or are you just on the EDDI personality?

**Comment by Tkael** [comment] 2018-09-17 12:17
Duplicate of #833 and #844.

**Closed as completed** 2018-09-17 12:21 UTC
