### ISSUE TITLE
Frontier API fails

### ISSUE THREAD

**Issue by Timnus** [EDCD/EDDI#1089] opened 2019-01-15 18:36 UTC
## EDDI version in which issue found
3.3.2

## Steps to reproduce

1. open program. Frontier tab. enter login info requested. fails to connect. wait a day. still fails.
2. Another program requiring frontier API connects successfully

## Expected
open web page to hit button to approve query for API key

## Observed
programs displays "unable to login. this is usually a temporary issue with frontier's service.

## Investigation
opened another program that uses frontier API. connects and web page opens with approve button.
successful.

**Comment by Hoodathunk** [comment] 2019-01-15 18:43
FDEV changed the authentication protocol for cAPI for the chapter 4 update and the maturity for their implementation for apps (vs websites) was considerably delayed.

We now have all the tools we need and are working on it.

Highly recommend you review other resources (FDEV forum, Discord, existing EDDI GitHub issues, etc) before generating an issue to ensure it hasn't already been addressed.

**Comment by Tkael** [comment] 2019-01-16 01:32
Duplicate of #1069 (amongst other tickets).

**Closed by Tkael** 2019-01-16 01:32 UTC
Labels: duplicate

**Comment by Tkael** [comment] 2019-01-29 02:12
Check the releases page and download the latest version (3.3.4-rc1), which includes support for the revised Frontier API.

**Comment by Furiant** [comment] 2019-02-15 13:20
I don't know if this is still the same issue, but as of this morning's 3.3.6 update the application will not connect to the API. It opens the auth page, I click Login, get the prompt to open EDDI (I don't know why), but EDDI still shows "Frontier API connection not operational" and "Frontier API status: Not Connected". Other services are logged in. It was working last night (3.3.5 I guess, whatever the prior release was).

**Comment by Tkael** [comment] 2019-02-16 16:19
See #1185  .
