### ISSUE TITLE
EDDI high CPU usage and ship monitor freezing (in VA)

### ISSUE THREAD

**Issue by jimbot70** [EDCD/EDDI#1182] opened 2019-02-15 04:31 UTC
## EDDI version in which issue found
EDDI 3.3.5, Voice Attack 1.7.3

Edit-3.3.6 has the same issue for me

## Steps to reproduce

Launch EDDI through Voice Attack

## Expected
Normal EDDI function,

## Observed
Voice attack starts up and runs fine until EDDI plugin 3.3.5 starts up and immediately starts using 15-20% of my CPU and then rises to 100% usage if left running for a few minutes.

Running EDDI standalone produces a 15-20% constant CPU usage with spikes to 40% usage ever time I dock, undock or change ships that last for 10-20 seconds before dropping back down to 15% again.

In both the standalone and when running in Voice attack text to speech responses are delayed by 10-20 seconds, changing tabs takes several seconds and scrolling in the ship and voice response list is slow with it not scrolling for a second after I start.

-edit- It's also extremely slow to respond to ship changes.   EDDI still thinks I am in my Cobra after changing ships several times since then.

## Investigation
I have had similar issues in the past when one of EDDIs files gets corrupted by something but my usual fixes have not worked.  I have tried a clean reinstall several times(removing all of the leftover files in the EDDI folder in appdata and Voice Attack, I have tried downgrading to 3.3.4 and it also has the same problems after I run it with Voice Attack.  I have reinstalled Voice Attack and run EDDI only without any other Voice Attack plugins with the same results.

On a clean install it'll eventually drop to under 3% usage on the initial run after an install if I run it standalone but after I relaunch it or run it through Voice Attack the problems start up again.

**Comment by jimbot70** [comment] 2019-02-15 06:10
I think it has something to do with the ship monitor page.  Trying to open that page in the Voice Attack launched EDDI crashes it entirely and in the standalone version it's extremely laggy compared to every other page.

**Comment by antiriad1974** [comment] 2019-02-15 22:07
I also have this issue - both the high processor usage (up to 50%) and the Ship Monitor page causing crashes.  Makes EDDI unusable for me at the moment unfortunately.

**Comment by antiriad1974** [comment] 2019-02-16 00:03
Some further testing... Processor use of VoiceAttack when EDDI plugin is enabled begins at 15-20% on loading up, then jumps to 22-25% once the EDDI plugin becomes active - stays there for around 1 min, then jumps to 45-50% processor usage and stays there - never drops below 42%.  When the EDDI plugin is disabled, VoiceAttack processor usage sits between 0-2%.  EDDI version 3.3.6.  Updated to this version today from 3.3.4.  This issue did not occur with 3.3.4.  If I can provide any further information, let me know what you need.

**Comment by Tkael** [comment] 2019-02-16 05:06
Confirmed... we're looping. Only with the Ship Monitor and only with VoiceAttack. @Hoodathunk and I will get it fixed.

**Comment by hoksilato2** [comment] 2019-02-16 18:16
When I try to open Ship monitor EDDI not response at several minutes and some interaction on this monitor stack EDDI. I see too that text in Spanish is not in the correct order. Eddi's log show this errors:

![image](https://user-images.githubusercontent.com/18234212/52903531-10476480-321f-11e9-9b6c-5237c48dc969.png)

Maybe this helps. I take the opportunity to give you support for this great work that you are doing.

**Comment by Tkael** [comment] 2019-02-16 20:50
@hoksilato2 The bug we're seeing doesn't generate logs. This looks like it may be a different issue. Is this in VoiceAttack?

**Comment by Tkael** [comment] 2019-02-17 04:18
We're preparing a fix for this issue.

**Comment by hoksilato2** [comment] 2019-02-17 09:30
Is with VoiceAttack yes :)

**Closed** 2019-02-18 19:17 UTC
Labels: 6. bug / not up to spec, PR submitted
