### ISSUE TITLE
It will not connect to the frontier API now that it has updated. says "only one instance of EDDI may be open at one time"

### ISSUE THREAD

**Issue by Msirike** [EDCD/EDDI#1787] opened 2020-05-26 02:55 UTC
## EDDI version in which issue is found
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable)
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

## Expected
[Describe what you expected to happen]

## Observed
[Describe what happened instead]

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment] 2020-05-26 08:14
Duplicate of #1786 and #1735. We're aware of the issue and working on it.

**Closed as completed by Tkael** 2020-05-26 08:14 UTC
Labels: duplicate
