### ISSUE TITLE
Passenger Mission count is reported incorrectly.

### ISSUE THREAD

**Issue by SmartShots** [EDCD/EDDI#2046] opened 2020-12-23 12:28 UTC
What happens:
I have been doing Robigo runs from Robigo Mines in Robigo to the Sirius Atmospherics POI in Sirius. I take 9 passenger missions at Robigo Mines, take the passengers to the destination and come straight back to Robigo Mines to hand in the passenger missions.

When I get back to Robigo EDDI tells me I have 1 mission to hand in at Robigo Mines, instead of the 9 missions I actually have to hand in there.

I hand the missions in but EDDI doesn't seem to realise that I have handed them all in. It seems to see them all as 1 mission because later I will get a message stating that I have however many failed missions when I don't have any failed missions. Sometimes it will also come up the next day when I open up VA/EDDI with loads of messages saying your mission for (whoever) has failed over and over until it has gone through them all. Again when I have no failed missions. I've actually disabled the 'Failed Mission' speech response now because of this.

Expected:
I expect the mission count to be reported correctly and EDDI to say I have the 9 missions I actually have to hand in and not to tell me I have loads of failed missions when I haven't.

Steps to reproduce
1. Do Robigo runs with EDDI running.

Configuration
* Version
  * EDDI Version: 3.7.1
  * VoiceAttack Version: 1.8.7.5 (pre-release)

Investigation: None

My EDDI Log from this morning:
2020-12-23T10:55:53 [Info] EDDI:.ctor On live
2020-12-23T10:55:53 [Info] VoiceAttackPlugin:VA_Init1 Initialising EDDI VoiceAttack plugin
2020-12-23T10:55:53 [Info] EDDI:.ctor EDDI 3.7.1 starting
2020-12-23T10:55:53 [Info] StatusMonitor:.ctor Initialized Status monitor
2020-12-23T10:55:53 [Info] ShipMonitor:.ctor Initialized Ship Monitor
2020-12-23T10:55:53 [Info] MissionMonitor:initializeMissionMonitor Initialized Mission monitor
2020-12-23T10:55:53 [Info] MaterialMonitor:.ctor Initialized Material monitor
2020-12-23T10:55:53 [Info] CrimeMonitor:initializeCrimeMonitor Initialized Crime monitor
2020-12-23T10:55:53 [Info] CargoMonitor:initializeCargoMonitor Initialized Cargo monitor
2020-12-23T10:55:53 [Info] EDDNResponder:.ctor Initialized EDDN responder
2020-12-23T10:55:53 [Info] EDSMResponder:.ctor Initialized EDSM responder
2020-12-23T10:55:53 [Info] StarSystemSqLiteRepository:CreateOrUpdateDatabase Starsystem repository schema is version 2
2020-12-23T10:55:54 [Info] SpeechResponder:.ctor Initialized Speech responder
2020-12-23T10:55:54 [Info] VoiceAttackResponder:.ctor Started VoiceAttack responder
2020-12-23T10:55:59 [Info] EDDI:.ctor EDDI access to the Frontier API is enabled.
2020-12-23T10:56:00 [Info] EDDI:.ctor EDDI 3.7.1 initialised
2020-12-23T10:56:00 [Info] EDDI:Start Starting keepalive for EDDP monitor
2020-12-23T10:56:00 [Info] EDDI:Start Starting keepalive for Journal monitor
2020-12-23T10:56:00 [Info] EDDI:Start Starting keepalive for Mission monitor
2020-12-23T10:56:00 [Info] EDDI:keepAlive Starting EDDP monitor (0)
2020-12-23T10:56:00 [Info] EDDI:keepAlive Starting Journal monitor (0)
2020-12-23T10:56:00 [Info] EDDI:keepAlive Starting Status monitor (0)
2020-12-23T10:56:00 [Info] EDDI:Start Started EDDN responder
2020-12-23T10:56:00 [Info] EDDI:keepAlive Starting Mission monitor (0)
2020-12-23T10:56:00 [Info] EDDI:Start Starting keepalive for Status monitor
2020-12-23T10:56:00 [Info] EDDI:Start Started EDSM responder
2020-12-23T10:56:00 [Info] InaraResponder:Start Initialized Inara Responder
2020-12-23T10:56:00 [Info] EDDI:Start Started Inara Responder
2020-12-23T10:56:00 [Info] EDDI:Start Started Speech responder
2020-12-23T10:56:00 [Info] EDDI:Start Started VoiceAttack responder
2020-12-23T10:56:00 [Info] EDDI:eventFileHeader On live
2020-12-23T10:56:00 [Info] EDDI:eventLocation Location StarSystem: Robigo
2020-12-23T10:56:00 [Info] VoiceAttackPlugin:VA_Init1 EDDI VoiceAttack plugin initialization complete
2020-12-23T10:56:00 [Info] DataProviderService:syncFromStarMapService EDSM sync completed
2020-12-23T10:56:04 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:07 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:07 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:07 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:07 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:07 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:07 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:07 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:08 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:08 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:08 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:08 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:08 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:08 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:08 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:08 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:08 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:08 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:09 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:09 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:09 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:09 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:09 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:09 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:09 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:09 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:09 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:09 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:10 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:10 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:10 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:10 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:10 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:10 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:10 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:10 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:10 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:10 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:11 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:11 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:11 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:11 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:11 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:11 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:11 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:12 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:12 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:12 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:12 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:12 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:12 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:12 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:13 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:13 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:13 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:13 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:13 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:13 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:13 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:13 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:14 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:14 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:14 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:14 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:14 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:14 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:14 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:14 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:15 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:15 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:15 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:15 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:15 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:15 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:15 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:15 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:16 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:16 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:16 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:16 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:16 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:16 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:16 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:16 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:17 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:17 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:17 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:17 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:17 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:17 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:17 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:17 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:18 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:18 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:18 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:18 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:18 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:18 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:19 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:19 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:19 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:19 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:19 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:19 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:20 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:20 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:20 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:20 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:20 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:20 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:20 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:20 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:21 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:21 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:21 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:21 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:22 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:22 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:22 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:22 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:22 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:22 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:22 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:22 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:23 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:23 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:23 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:23 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:23 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:24 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:24 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:24 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:24 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:24 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:25 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:25 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:25 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:25 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:25 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:25 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:26 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:26 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:26 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:26 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:27 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:27 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:27 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:27 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T10:56:27 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:27 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T10:56:28 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T10:56:28 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T11:01:42 [Info] EDDI:eventFileHeader On live
2020-12-23T11:02:18 [Info] EDDI:eventLocation Location StarSystem: Robigo
2020-12-23T11:20:10 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI undocked))
2020-12-23T11:21:02 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T11:21:51 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T11:25:15 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T11:26:05 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T11:37:28 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI undocked))
2020-12-23T11:38:23 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T11:39:13 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T11:42:53 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T11:43:43 [Info] EDDI:eventJumped Jumped to Robigo
2020-12-23T12:10:57 [Info] VoiceAttackPlugin:triggerVACommands Executed command ((EDDI undocked))
2020-12-23T12:11:53 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T12:12:40 [Info] EDDI:eventJumped Jumped to Sothis
2020-12-23T12:16:43 [Info] EDDI:eventJumped Jumped to Wredguia TH-U c16-18
2020-12-23T12:17:38 [Info] EDDI:eventJumped Jumped to Robigo

**Comment by Tkael** [comment] 2020-12-23 12:32
Thanks for the report. We're already aware of this issue. A fix is already merged into the in-development version and will be available upon EDDI's next release. o7

**Comment by Tkael** [comment] 2020-12-23 12:33
Closed as duplicate of #2020.

**Closed as completed by Tkael** 2020-12-23 12:32 UTC
Labels: duplicate
