### ISSUE TITLE
Possible bug with {INT:Ship cargo capacity}

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2503] opened 2023-01-23 14:52 UTC
## What's Wrong (please be as specific as possible)
every time there is a cargo event ((EDDI cargo)) or my other cargo commands, this results wrong. It also seems to give the first ship cargo capacity correctly when logging in, but does not refresh it when swapping ship

**Comment by Tkael** [comment] 2023-01-24 08:09
Duplicate of #2482.

**Closed as completed by Tkael** 2023-01-24 08:09 UTC
Labels: duplicate
