### ISSUE TITLE
Ship cargo capacity: {INT:Ship cargo capacity} tons

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2489] opened 2023-01-13 16:50 UTC
### Expected
Result is zero

### Configuration
* Version [Please give full version numbers here, not just "latest" or "current"]
  latest EDDI

**Comment by FireSammy** [comment] 2023-01-13 17:08
Used to work just fine

**Comment by Darkcyde13** [comment] 2023-01-13 23:05
Sounds like the same thing as reported in #2482.

**Comment by Tkael** [comment] 2023-01-14 04:24
Thanks for the report. Closing as a duplicate of #2482.

**Closed as completed by Tkael** 2023-01-14 04:24 UTC
