### ISSUE TITLE
90

### ISSUE THREAD

**Issue by blutm8** [EDCD/EDDI#1000] opened 2018-12-15 14:44 UTC
## EDDI version in which issue found
3.3.0-b1

## Steps to reproduce

![image](https://user-images.githubusercontent.com/33543821/50044224-71688580-0080-11e9-93ab-723cead48b4f.png)

speech response is telling me that the planet is landable with a 0-day rotational period

## Expected
well, I guess "landable but tidally locked with a rotational period of 75.1 days" and I think it should tell me about the materials to be found on the ground, which it doesn't 

## Observed
in all versions, even in the release versions of EDDI

## Investigation
just scanning planets. It has happened in chapter 3 already

**Comment by Tkael** [comment] 2018-12-15 16:07
Closing as a duplicate of #990 for the rotation period issue.

Note that EDDI will only tell you about materials with either "good" or "great" material concentrations, and that in future it'd be helpful if you included the name and system of the specific body where you had an issue like this (or a copy of the applicable player journal, if possible).

Player journals are written to `[your Windows Saved Games folder]\Frontier Developments\Elite Dangerous`.

**Closed by Tkael** 2018-12-15 16:07 UTC
