### ISSUE TITLE
Unable to enter home station

### ISSUE THREAD

**Issue by CyberFoxx** [EDCD/EDDI#832] opened 2018-09-08 11:21 UTC
## EDDI version in which issue found
EDDI v3.0.3 standalone

## Steps to reproduce

1. Commander Details tab
2. Enter home system: Run
3. Attempt to enter home station: Leif Enterprise

## Expected
EDDI accepting Leif Enterprise as the home station.

## Observed
EDDI displays red box around the text entry box for the station. Upon changing focus from the text entry box, the station name is cleared.

## Investigation
Could it be because Leif Enterprise is an asteroid station in a ring?

**Comment by Hoodathunk** [comment] 2018-09-08 16:03
The API server crashed hard last night. Please check your API connection and let us know the if re-logging in corrects this.

**Comment by Tkael** [comment] 2018-09-08 16:32
That's not it. EDDI is checking http://api.eddp.co/systems/Run to determine whether the system and station names are valid. Smithport is listed but Leif Enterprise isn't listed. Consequently, EDDI sees Leif Enterprise as invalid.

We've found that this data source (a legacy server from EDDI's prior dev which we do not control) isn't always reliable and are migrating to a different source. If Leif Enterprise was recently added to the game, the current data source might be updated to include it. If not, the new data source we're in the process of migrating to should remain more up to date.

**Comment by Hoodathunk** [comment] 2018-09-08 17:06
Yup, makes sense. I yield to your superior knowledge on EDDP mechanics. 😉

All the more reason for your porting our EDDB data queries from EDDP to EBGS!

**Comment by CyberFoxx** [comment] 2018-09-08 23:30
Ah, that explains it. Well, I shall wait patiently in the mean time. EDDI at least knowing my home system is good enough for me for now.

**Comment by Tkael** [comment] 2018-09-09 03:39
Thanks for understanding. We're eager to improve this area of the code base.
Closing as a duplicate of #97.

**Closed by Tkael** 2018-09-09 03:39 UTC
