### ISSUE TITLE
Alert to send files

### ISSUE THREAD

**Issue by rj16066** [EDCD/EDDI#192] opened 2017-10-28 15:42 UTC
## Steps to reproduce

When ever I land at a station, it says there is a EDDI error and to send the file. 

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment] 2017-10-28 16:23
Thanks for reporting, commander, but this is a duplicate of #181 and #183. No new files provided. Closing as redundant.

**Closed by Tkael** 2017-10-28 16:23 UTC
