### ISSUE TITLE
error in commodity definition (intermittent)

### ISSUE THREAD

**Issue by hairagon** [EDCD/EDDI#205] opened 2017-11-03 16:04 UTC
## Steps to reproduce

obtain rare goods
## Expected
nothing

## Observed
eddi tells me error in commodity definition

## Investigation
none

**Comment by Tkael** [comment] 2017-11-04 01:08
Duplicate of #181. We're working on a fix. Thanks for reporting.

**Closed by Tkael** 2017-11-04 01:08 UTC
Labels: duplicate
