### ISSUE TITLE
Limpet reporting error

### ISSUE THREAD

**Issue by cmdrbarneyfive** [EDCD/EDDI#357] opened 2018-01-24 15:23 UTC
## EDDI version in which issue found
[2.4.5]

## Steps to reproduce

EDDI audibly reports "You have a limpet controller but are not carrying any limpets" whether or not there are limpets on board.

That message would actually be a great reminder, but I've taken to not listening to it anymore. That cost me a round trip BACK to the starport on the one occasion when I really didn't have any limpets on board.

It's only an annoyance issue but would be nice if it was looked into some time. Thanks guys!

**Comment by Tkael** [comment] 2018-01-24 18:07
We're aware of it and @hoodathunk had been working on some changes related to cargo/limpets. We've also hopeful that the next journal release will help fill some gaps in reporting used limpets.

**Comment by Tkael** [comment] 2018-01-24 18:08
Duplicate of #52.

**Closed** 2018-01-25 03:50 UTC
