### ISSUE TITLE
Voice Attack 100% CPU

### ISSUE THREAD

**Issue by Wasp0** [EDCD/EDDI#1254] opened 2019-03-20 09:33 UTC
## EDDI version in which issue is found. 3.3.7-b1
[Please give the full version number here, not just "latest" or "current"]

## VoiceAttack version in which issue is found (as applicable). 1.7.3
[Skip this section if VoiceAttack was not running when the issue occurred. Please give the full version number here, not just "latest" or "current"]

## Steps to reproduce. Open voice attack with EDDI Plugin enabled.
1. [Give the fullest and most reproducible steps you can]
2. [The more reproducible, the better our chances of fixing it]

## Expected. To NOT shoot CPU Usage straight up to 100%
[Describe what you expected to happen]

## Observed. Within 30 secs my CPU usage was 100% with Voice Attack the culprit
[Describe what happened instead]

## Investigation. Opened VA Plugin Manager, disabled EDDI plug in, VA CPU Usage dropped to normal levels (Around 8%
[Any investigation you have done, regression tests against earlier versions, etc]

I had this issue a few weeks back and upgraded to EDDI ver 3.3.7.b1 and this solved the issue. However tonight it happened again, and made the game (Elite Dangerous) un-playable. I have had to disable EDDI plug in within VA to be able to play Elite Dangerous again.

Thank you

**Comment by Tkael** [comment] 2019-03-20 13:00
duplicate of #1238.

**Closed** 2019-03-20 13:01 UTC
Labels: duplicate

**Comment by Wasp0** [comment] 2019-03-20 13:05
Hi Brian,

Sorry but it is not a duplicate of #1238!

I read that 1238 is when more than one ship? This happens to me when I first open VA and ED without changing ships as ticket number 1238 implys.
I will check again tonight, as not in game at the moment and see if I can replicate it again and give more details.

Thank you

Steve
