### ISSUE TITLE
Does not see all my ships

### ISSUE THREAD

**Issue by RedBaron1947** [EDCD/EDDI#317] opened 2017-12-25 19:14 UTC
## EDDI version in which issue found
[]
V2.4.6-b2
I own  4 ships in ED  and yet EDDI only see 3 and my Beluga is not mentioned as Beluga 1, and my Python is not even on the list, it just says 'stands ready' until before my last update this was not a problem, I've attached a screen shot the ship monitor page showing what I mean.

![eddi](https://user-images.githubusercontent.com/20424977/34342432-c3f33048-e9a7-11e7-8634-200cb3eca2f8.PNG)
Thanks
JM.

**Comment by Tkael** [comment] 2017-12-26 02:28
Are you logged into the Frontier API? If not, try logging in and then switching to each ship. Take about a minute on each ship... The export button will be enabled once the Frontier API data has been synced.

**Comment by Tkael** [comment] 2017-12-26 02:29
This may also be related to #305. If so, the cause should be fixed by the next release.

**Comment by Tkael** [comment] 2018-01-04 02:35
Closing as a duplicate of #305.

**Closed by Tkael** 2018-01-04 02:35 UTC
