### ISSUE TITLE
submit error report

### ISSUE THREAD

**Issue by dalvon** [EDCD/EDDI#206] opened 2017-11-04 04:08 UTC
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/1442923/eddi_issue.zip)
## Steps to reproduce

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]

## Observed
[describe what happened instead]

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment] 2017-11-04 20:21
Duplicate of #181. Fix is in testing. Thanks!

**Closed by Tkael** 2017-11-04 20:21 UTC
Labels: duplicate
