### ISSUE TITLE
v2.4.3 => Pause() function doesn't seem to work anymore

### ISSUE THREAD

**Issue by aeterna426** [EDCD/EDDI#212] opened 2017-11-05 04:58 UTC
As in topic

**Comment by Tkael** [comment] 2017-11-05 05:13
Which voice are you using, and is phonetic speech enabled?

**Comment by JCalvertJoshua** [comment] 2017-11-05 09:28
I can confirm it isn't working since 2.4.3
Like before 2.4.3 I'm using Ivona Emma and phonetic is enabled. 
I noticed the Pause() function in FSD engaged is ignored since 2.4.3

**Comment by aeterna426** [comment] 2017-11-05 16:11
Phonetic Speech is enabled. I too am using Ivona (various voices). So far no luck in using Pause() function. Ok, I will also enable verbose log of an 'FSD engaged' event and few additional ones. Although in previous versions everything was ok.

**Comment by JCalvertJoshua** [comment] 2017-11-05 16:15
[eddi.log](https://github.com/EDCD/EDDI/files/1444194/eddi.log)
Here's my verbose log with two hyperspace jumps. The first was using the default script (pause 5000ms) and the second was with a copied personality where I changed the pause to 30000ms. In both case the speech started at the same time the 5 second countdown of the FSD started.

**Comment by JCalvertJoshua** [comment] 2017-11-05 16:42
Maybe this is something causing it. I had some old log files and compared one with the one I just sent (see attached file). In the old version (first part of the file) it says  xml:lang="en-GB" and in the current version it says xml:lang = en-GB
and then it gives an error: SpeechService:speak [W] speech failed:  System.FormatException: XML content not valid. ---> System.Xml.XmlException: 'en-GB' is an unexpected token. The expected token is '"' or '''. Line 1, position 115.

Maybe it's just missing the " " around en-GB when feeding the synthesizer.
[fsdtest.txt](https://github.com/EDCD/EDDI/files/1444227/fsdtest.txt)

**Comment by richardbuckle** [comment] 2017-11-05 17:10
That would account for it.

**Comment by Tkael** [comment] 2017-11-05 17:37
If so then I'm already on it. PR submitted.

**Comment by JCalvertJoshua** [comment] 2017-11-05 19:30
Fixed in 2.4.4 Thanks guys.

**Closed** 2017-11-05 20:57 UTC
Labels: 5. priority / painful
