### ISSUE TITLE
Completion of multiple Passenger missions at the same time not detected

### ISSUE THREAD

**Issue by netchild** [EDCD/EDDI#2047] opened 2020-12-23 13:01 UTC
Hi,

if I have multiple passenger missions to the same destination, all of them succeed at the same time. Only one of them is recorded in the Mission Monitor as succeeded, and as such only one missions is announced to be completed.

Bye,
Alexander.

**Comment by Tkael** [comment] 2020-12-23 13:06
Thanks, we're already aware and we've already implemented a fix for the next release. Duplicate of #2020 and #2046.

**Closed as completed by Tkael** 2020-12-23 13:06 UTC
Labels: duplicate
