### ISSUE TITLE
EDDI 3.3.6 and .4 crash on double click, it works under VA.

### ISSUE THREAD

**Issue by RedSerious** [EDCD/EDDI#1217] opened 2019-03-03 07:43 UTC
## EDDI version in which issue found
3.3.4 and 3.3.6

## Steps to reproduce

1. Double click on EDDI icon
2. The dialogue "EDDI has stopped working" pops up.

## Expected
After the double click, I expect EDDI to launch and show the GUI.

## Observed
After double click it crashes immediately without showing GUI. 

## Investigation
The app doesn't show GUI, crashes but while the dialogue is open, eddi.exe is running in Task manager.

Running on Windows 8.1. Earlier today it was working fine. Turned off PC, came back hours later tried to run and stumbled upon this issue.

**Can't find eddi.log** on the installation folder, any help to where to find it?

I saw one post about 3.3.4 crashing due to trial TTS and missionobserver but after running Elite Dangerous, the problem persists.
HOWEVER: If I run Voice attack (wich has EDDI as a plug in), EDDI runs without a problem, I tested it on a station to scan for updates on local market and the TTS was triggered with the best proces and savings. VA version is 1.7.3.

This is window's error report:

Nombre del evento de problema:	CLR20r3
  Firma del problema 01:	EDDI.exe
  Firma del problema 02:	1.0.0.0
  Firma del problema 03:	5c6642b2
  Firma del problema 04:	System.Xml
  Firma del problema 05:	4.7.3062.0
  Firma del problema 06:	5ab9528a
  Firma del problema 07:	b85
  Firma del problema 08:	27
  Firma del problema 09:	IOIBMURHYNRXKW0ZXKYRVFN0BOYYUFOW
  Versión del sistema operativo:	6.3.9600.2.0.0.256.48
  Id. de configuración regional:	2058
  Información adicional 1:	5861
  Información adicional 2:	5861822e1919d7c014bbb064c64908b2
  Información adicional 3:	bb02
  Información adicional 4:	bb02c3b29c3f075104f1d0629e885cfc

It's in spanish, but I can translate if needed.

**Comment by Tkael** [comment] 2019-03-03 08:50
Duplicate of #1216. Please disable the Galnet monitor until this is resolved.

**Comment by Tkael** [comment] 2019-03-03 08:50
`eddi.log` is located at `%APPDATA%/EDDI`.

**Closed by Tkael** 2019-03-03 08:50 UTC
