### ISSUE TITLE
Star scan reports still repeating

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1145] opened 2019-01-31 21:15 UTC
3.3.4-rc3

Journal:
```
{ "timestamp":"2019-01-31T21:06:58Z", "event":"Music", "MusicTrack":"Supercruise" }
{ "timestamp":"2019-01-31T21:07:14Z", "event":"StartJump", "JumpType":"Hyperspace", "StarSystem":"LHS 1383", "SystemAddress":9466242147729, "StarClass":"M" }
{ "timestamp":"2019-01-31T21:07:19Z", "event":"Music", "MusicTrack":"NoTrack" }
{ "timestamp":"2019-01-31T21:07:21Z", "event":"FSDTarget", "Name":"Piscium Sector XZ-X a1-3", "SystemAddress":58138287819544 }
{ "timestamp":"2019-01-31T21:07:32Z", "event":"ReceiveText", "From":"", "Message":"$COMMS_entered:#name=LHS 1383;", "Message_Localised":"Entered Channel: LHS 1383", "Channel":"npc" }
{ "timestamp":"2019-01-31T21:07:32Z", "event":"FSDJump", "StarSystem":"LHS 1383", "SystemAddress":9466242147729, "StarPos":[-45.84375,-19.87500,-52.53125], "SystemAllegiance":"", "SystemEconomy":"$economy_None;", "SystemEconomy_Localised":"None", "SystemSecondEconomy":"$economy_None;", "SystemSecondEconomy_Localised":"None", "SystemGovernment":"$government_None;", "SystemGovernment_Localised":"None", "SystemSecurity":"$GAlAXY_MAP_INFO_state_anarchy;", "SystemSecurity_Localised":"Anarchy", "Population":0, "JumpDist":23.215, "FuelUsed":0.702144, "FuelLevel":1.869016 }
{ "timestamp":"2019-01-31T21:07:32Z", "event":"Music", "MusicTrack":"Supercruise" }
{ "timestamp":"2019-01-31T21:07:37Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"LHS 1383 A", "BodyID":1, "Parents":[ {"Null":0} ], "DistanceFromArrivalLS":0.000000, "StarType":"M", "StellarMass":0.222656, "Radius":276052032.000000, "AbsoluteMagnitude":10.803558, "Age_MY":11906, "SurfaceTemperature":2317.000000, "Luminosity":"V", "SemiMajorAxis":326283395072.000000, "Eccentricity":0.278157, "OrbitalInclination":33.881714, "Periapsis":285.202576, "OrbitalPeriod":1018144128.000000, "RotationPeriod":101774.875000, "AxialTilt":0.000000 }
{ "timestamp":"2019-01-31T21:07:37Z", "event":"FSSDiscoveryScan", "Progress":0.779382, "BodyCount":3, "NonBodyCount":0 }
{ "timestamp":"2019-01-31T21:07:37Z", "event":"Scan", "ScanType":"Detailed", "BodyName":"LHS 1383 B", "BodyID":2, "Parents":[ {"Null":0} ], "DistanceFromArrivalLS":2537.581787, "StarType":"L", "StellarMass":0.101563, "Radius":176188512.000000, "AbsoluteMagnitude":13.761383, "Age_MY":11906, "SurfaceTemperature":1469.000000, "Luminosity":"V", "SemiMajorAxis":715313840128.000000, "Eccentricity":0.278157, "OrbitalInclination":33.881714, "Periapsis":105.202583, "OrbitalPeriod":1018144128.000000, "RotationPeriod":86569.421875, "AxialTilt":0.000000 }
{ "timestamp":"2019-01-31T21:07:41Z", "event":"Music", "MusicTrack":"SystemMap" }
{ "timestamp":"2019-01-31T21:07:42Z", "event":"Music", "MusicTrack":"Supercruise" }
{ "timestamp":"2019-01-31T21:07:59Z", "event":"FuelScoop", "Scooped":0.434841, "Total":2.303856 }
{ "timestamp":"2019-01-31T21:08:31Z", "event":"Music", "MusicTrack":"SystemAndSurfaceScanner" }
{ "timestamp":"2019-01-31T21:08:33Z", "event":"Music", "MusicTrack":"Supercruise" }
{ "timestamp":"2019-01-31T21:08:41Z", "event":"Music", "MusicTrack":"SystemMap" }
{ "timestamp":"2019-01-31T21:08:42Z", "event":"Music", "MusicTrack":"Supercruise" }
{ "timestamp":"2019-01-31T21:09:33Z", "event":"FuelScoop", "Scooped":1.233917, "Total":3.537767 }
{ "timestamp":"2019-01-31T21:09:49Z", "event":"FSDTarget", "Name":"Piscium Sector XZ-X a1-3", "SystemAddress":58138287819544 }
{ "timestamp":"2019-01-31T21:09:49Z", "event":"SupercruiseExit", "StarSystem":"LHS 1383", "SystemAddress":9466242147729, "Body":"LHS 1383 A", "BodyID":1, "BodyType":"Star" }
{ "timestamp":"2019-01-31T21:09:49Z", "event":"Music", "MusicTrack":"Exploration" }
{ "timestamp":"2019-01-31T21:09:54Z", "event":"Music", "MusicTrack":"MainMenu" }
```

speechresponder.out:
```
 Jump in progress. Mule is in transit to the L H S 1 3 8 3 system. You are no longer in Federation space. This is your first visit to this system. This system is not populated.
Fuel reserves below 50%, commander

L-class brown dwarf detected.
L-class brown dwarf detected.
L-class brown dwarf detected.
L-class brown dwarf identified.
L-class brown dwarf identified.
L-class brown dwarf identified.
L-class brown dwarf detected.
L-class brown dwarf detected.
a very common M-class star detected.
a very common M-class main sequence star identified.
L-class brown dwarf detected.
L-class brown dwarf detected.
 Refueled
 returned to normal space close to star L H S 1 3 8 3 A.
```

**Comment by Tkael** [comment] 2019-02-02 05:53
Merging and closing as a duplicate of #1041.

**Closed by Tkael** 2019-02-02 05:53 UTC
Labels: 8. inconvenience / annoyance, duplicate
