### ISSUE TITLE
Status analysis mode not updating in srv correctly

### ISSUE THREAD

**Issue by Orsum-VR** [EDCD/EDDI#1388] opened 2019-07-08 15:10 UTC
## EDDI version in which issue is found
3.4.1

## VoiceAttack version in which issue is found (as applicable)
1.7.5

## Steps to reproduce
using the value Status analysis mode while in SRV on voiceattack

## Expected
It should change respectively from analysis (true) to combat (false)

## Observed
It stays in combat (false) mode

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment] 2019-07-15 00:53
I was able to replicate this issue, but I'm afraid the problem is with the status.json file written by Frontier Developements - the flag for the mode change is not changed when you switch modes in an SRV.

**Comment by Tkael** [comment] 2019-07-15 02:04
I've posted a request to address this bug in the forums at https://forums.frontier.co.uk/threads/journal-docs-for-v3-4.508702/post-7899620, but I'm afraid we're at the mercy of the official devs for a fix. 
Closing as un-actionable for the time being.

**Closed by Tkael** 2019-07-15 02:04 UTC
Labels: frontier's bug / change
