### ISSUE TITLE
Removed module(s) still active in Shipmonitor

### ISSUE THREAD

**Issue by DeeM77** [EDCD/EDDI#315] opened 2017-12-23 15:18 UTC
## EDDI version in which issue found
[2.4.6-b2]

## Steps to reproduce

1. Add and remove a module from ship from a compartment.

## Expected
Module should not be reported in the compartment. 

## Observed
Module is still fully reported in VA with the command "{TXT:Ship compartment n module}"
Also the module is still reported within the shipmonitor,json

## Investigation
Deleted the shipmonitor.json to have EDDI rebuild a new one. Then tried to add/remove the module again. It is still reported. If you close and open EDDI it will be gone. Sometimes the modules will be gone but in 60% the module stays behind in the shipmonitor.json 

If you replace the module with another module it is reported correctly. This happens only when the compartment is emptied. 

I have attached my shipmonitor.json
[shipmonitor.zip](https://github.com/EDCD/EDDI/files/1584201/shipmonitor.zip)

**Comment by Tkael** [comment] 2017-12-23 17:41
I suspect this will be related to #305, but unfortunately I'm not at my dev pc this week.
If it is the same as #305, it should be fixed in the next release.

**Comment by Tkael** [comment] 2018-01-04 02:35
Closing as a duplicate of #305.

**Closed by Tkael** 2018-01-04 02:35 UTC
