### ISSUE TITLE
Language settings are not preserved across standalone and VoiceAttack instances

### ISSUE THREAD

**Issue by mrmauz** [EDCD/EDDI#1367] opened 2019-06-17 22:34 UTC
## EDDI version in which issue is found: 
3.4.1 rc-1 (happening since always though...)

## VoiceAttack version in which issue is found (as applicable)
1.7.5.31 (i know this is a beta but it was happening with older releases as well)
i'm using VA with 3 HCS voce packs ATM (Celeste, Orion and Carina) although the problem was present even with only Celeste installed, dunnow if it could be related though

## Steps to reproduce
-open the game as usual after launching VA with HCS and EDDI personalities installed
-start playing
-listen to EDDI voice speaking about celestial bodies

## Expected
EDDi speaking English

## Observed
-notice the italian words leaking in between the spoken english

## Investigation
tried many things: downgrading, installing new windows VoicePack (currently using Ivona's Amy), reverting to the default personality, all documented on the forum but with no luck

attached is a trascriptions of EDDI in the last week.

[speechresponder.txt](https://github.com/EDCD/EDDI/files/3299084/speechresponder.txt)

no need to read it all, if you like i extrapolated the most important parts here:
https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/post-7842516

so far the only solution has been deleting the It localization folder (or zipping its content) until the next update, obviously!
:)

hope it's enough material to get you started, feel free to write me if i can be of assistance in any way!

Mauz AKA cmdr John de Mauzentia

**Comment by mrmauz** [comment] 2019-06-17 22:35
forgot to mention: Italian is my PC's default language

**Comment by Tkael** [comment] 2019-06-18 00:20
1. If you are using a custom personality then switch back to the default personality and make sure that it is still occurring there?

2. If you are using VoiceAttack, please test whether the same problem occurs when you are running EDDI standalone and let us know.

**Comment by mrmauz** [comment] 2019-06-18 09:17
1) i already tried that (and tried to mention it when saying "reverting to the default personality", sorry for my bad english mate! ;) )

2)as a standalone EDDI works just like intended, so you must be onto something, any suggestion?

p.s. thanks for the prompt answer :)

[speechresponder.txt](https://github.com/EDCD/EDDI/files/3300757/speechresponder.txt)

**Comment by Tkael** [comment] 2019-06-18 12:39
Ok. So we seem to have an issue with VoiceAttack and EDDI thread cultures. 

Please review VoiceAttack's help file, you can replace calls for {DEC:variablename } with {DECINV:variableName} and replace calls for {EXP:expression} with {EXPDECINV:expression}. This **might** prevent VoiceAttack from reasserting the Windows thread culture. You can check the values of the tokens '{STATE_CULTURE}' and '{STATE_UICULTURE}' to check VoiceAttack's culture settings.

**Comment by mrmauz** [comment] 2019-06-18 20:02
i'm afraid i have to look even dumber than i really am abut you're talking chinese to me... where should i be looking for the variables and tokens you mentioned? is it in VA's EDDI profile? i didn't modify at all EDDI.vap (just the settings in EDDI's standalone window) and the HCS personality can't be modified at all...

**Comment by Tkael** [comment] 2019-06-22 21:45
Please try disabling all VA plugins except for EDDI. Does the issue remain?

**Comment by Tkael** [comment] 2019-06-28 20:39
Hi @mrmauz 	Have you had a chance to test disabling all VA plugins except EDDI?

**Comment by mrmauz** [comment] 2019-06-29 00:53
Hi Tkael, I'm sorry but IRL work hit me pretty hard; I'm afraid I won't have time to play 'til August... Can this be put on hold for that much time?

**Comment by Tkael** [comment] 2019-06-29 01:03
It can, but we plan on releasing new updates between now and then anyways so it may be better to close this for the time being. If the problem is still occurring when you return, ping us and we'll reopen it. o7

**Comment by mrmauz** [comment] 2019-06-29 01:32
It works for me!
o7

**Comment by mrmauz** [comment] 2019-07-22 11:23
> Hi @mrmauz Have you had a chance to test disabling all VA plugins except EDDI?

hi Tkael, had the chance to remove a little rust from my ship today, and tried what you asked: with VA active and only EDDI plugin activated i still have those leaks, version now running is 3.4.2-b1.
to add a little more to the mistery i can't open the config windows from inside VA. the {[Configure; Initialize; Minimize; Maximize; Restore; Close; Open] EDDI} simply doesn't work. can't tell if it used to work before because i never used it before (found out it was there only today ;) )

**Comment by Tkael** [comment] 2019-07-22 17:23
Acknowledged. The UI issue may or may not be related, but if you send me a copy of `eddi.log` from a session where you tried to open the UI we can see.
For the rest of it, we seem to be running into a bit of a conflict between VA and EDDI running in threads with different cultures. Needs some more thought

**Comment by Tkael** [comment] 2019-07-27 05:01
I set up a VM with the OS using a non-English language but EDDI appeared to translate everything correctly (running through VA) - I couldn't find any non-English leaks. Have you tried to replicate the issue on another computer? Do you have any tips that might help me to replicate this?

**Comment by mrmauz** [comment] 2019-07-29 14:41
I'm afraid I can't think of anything, are you familiar with team-viewer? Do you wanna try it?
I won't have the chance to try another pc for another couple months

**Comment by Tkael** [comment] 2019-07-30 01:40
I've basically familiar - the IT team has used it at work before. That said, if you're in Italy and I'm in California then we're looking at a pretty significant timezone difference and I'm not entirely sure I'd be able to get anything out of it that I wouldn't be able to get from your logs.

**Comment by mrmauz** [comment] 2019-07-30 08:13
I should have guessed that
Timing wouldn't be a big problem because I play a lot overnight and I could teach at least your first afternoon...

**Comment by Tkael** [comment] 2019-07-31 03:50
I've created [EDDI-3.4.2-b1-test.zip](https://github.com/EDCD/EDDI/files/3449741/EDDI-3.4.2-b1-test.exe.zip). This is a version of EDDI that is exactly the same as the current released beta, except with a little bit of extra logging around thread cultures. Would you please install and run this version (making sure that you play a session with localization leaks), then attach the resulting log from `%appdata%/EDDI` to this thread?

**Comment by mrmauz** [comment] 2019-07-31 15:06
[speechresponder.txt](https://github.com/EDCD/EDDI/files/3452525/speechresponder.txt

it's a short log but you should notice the words 'trattino' (dash), 'giallo arancione' (yellow orange), abd also the word 'Information:' at the end of the messages, mentioned in a different thread on the forum from another player.
if you can think of anything else i should do to help you help me just let me know

**Comment by Tkael** [comment] 2019-07-31 17:06
I'm afraid you grabbed the wrong file. I need the one called `eddi.log `.

**Comment by mrmauz** [comment] 2019-07-31 19:25
ooops
XD
here's the correct one (i hope at least)
[eddi.log](https://github.com/EDCD/EDDI/files/3453542/eddi.log)

**Comment by Tkael** [comment] 2019-08-01 04:54
It looks like that log file was from a session where you were running EDDI in standalone mode. I cannot use this, unfortunately. I need a log file where localization leaks occurred and which was generated by running the special version of EDDI I shared as a plugin for VoiceAttack.

**Comment by mrmauz** [comment] 2019-08-01 12:10
here's two logs from two game sessions consecutive, the first one (renamed) is a verbose log, the second is a normal log.
[eddi_verbose.log](https://github.com/EDCD/EDDI/files/3456579/eddi_verbose.log)
[eddi.log](https://github.com/EDCD/EDDI/files/3456580/eddi.log)

i started VA as usual and log out after each session. in both sessions the leaks were present.
hope i've done everything right this time
:)

**Comment by Tkael** [comment] 2019-08-02 03:31
Ok. Please test this version in VoiceAttack and let me know whether it resolves the localization leaks.
[EDDI-3.4.2-b1.test2.exe.zip](https://github.com/EDCD/EDDI/files/3459487/EDDI-3.4.2-b1.test2.exe.zip)

**Comment by mrmauz** [comment] 2019-08-02 22:54
i'm afraid it didn't... here's the log:
[eddi.log](https://github.com/EDCD/EDDI/files/3463097/eddi.log)

**Comment by Tkael** [comment] 2019-08-02 23:45
Here's another try...
[EDDI-3.4.2-b1.test3.zip](https://github.com/EDCD/EDDI/files/3463149/EDDI-3.4.2-b1.test3.zip)

**Comment by mrmauz** [comment] 2019-08-03 00:22
nope, still there :(
[eddi.log](https://github.com/EDCD/EDDI/files/3463189/eddi.log)

p.s. i'm really sorry i'm giving you all this trouble, keep in mind that i have found a (not so elegant) walk-around; all i have to do is erase the "**it**" folder inside "**...VoiceAttack\Apps\EDDI**" every time i receive an update so feel totally free to give up at any point, ok?

**Comment by Tkael** [comment] 2019-08-03 06:18
I wouldn't be able to do this for long if I wasn't pretty stubborn (or persistent, as I describe it in job interviews ;-)).
[EDDI-3.4.2-b1.test4.zip](https://github.com/EDCD/EDDI/files/3463432/EDDI-3.4.2-b1.test4.zip)
I actually think we're quite close now.

**Comment by mrmauz** [comment] 2019-08-03 10:37
i like the persistent way, (or stubbornness as i call it in my CV because in my line of work a little unpoliteness is not only accepted but even welcome) it's one of my best superpower too!
but it didn't do the trick this time, still no luck

[eddi.log](https://github.com/EDCD/EDDI/files/3463713/eddi.log)

**Comment by Tkael** [comment] 2019-08-03 19:22
Mind posting a screenshot of EDDI's UI so that I can see your language settings?

**Comment by mrmauz** [comment] 2019-08-03 19:35
<img width="684" alt="cattura 2" src="https://user-images.githubusercontent.com/49005595/62416210-996c1f80-b636-11e9-9e37-512464750111.png">
<img width="685" alt="cattura 1" src="https://user-images.githubusercontent.com/49005595/62416211-9a04b600-b636-11e9-8260-2320ba34d1cf.png">
<img width="684" alt="cattura 3" src="https://user-images.githubusercontent.com/49005595/62416217-9bce7980-b636-11e9-978c-4a67152e7cb2.png">

**Comment by Tkael** [comment] 2019-08-03 21:02
Hmm... your logs indicate that you are using the `Automatic` language setting but the UI clearly shows English. There may be a corrupted setting there. Here's what I want you to do:
1. Change your language setting to the `Automatic` language.
2. Install [this new test version.](https://github.com/EDCD/EDDI/files/3464334/EDDI-3.4.2-b1.test5.zip)
3. Run EDDI. Change the language setting back to the `English` language. 
4. Close EDDI.
5. Open EDDI again and verify that the language setting is `English`
6. Test for language leaks.
7. Send me **both** `eddi.log` **and** `eddi1.log`.

Thank you for your patience with this process. I know we've been at it for a little while now.

**Comment by mrmauz** [comment] 2019-08-03 21:30
hey Tkael, don't even mention it; i like this kind of stuff, testing and so on...
not of a least importance is the fact that you're literally helping me and not the opposite so... 
no good news again, here's the logs

[eddi1.log](https://github.com/EDCD/EDDI/files/3464355/eddi1.log)
[eddi.log](https://github.com/EDCD/EDDI/files/3464356/eddi.log)

**Comment by Tkael** [comment] 2019-08-04 08:24
Please repeat the steps above with this version.
[EDDI-3.4.2-b1.test6.zip](https://github.com/EDCD/EDDI/files/3464680/EDDI-3.4.2-b1.test6.zip)

**Comment by mrmauz** [comment] 2019-08-04 09:43
still no luck my friend...
:(

[eddi.log](https://github.com/EDCD/EDDI/files/3464769/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/3464770/eddi1.log)

**Comment by Tkael** [comment] 2019-08-04 16:19
Ok. So in the first log (eddi1.log) I see:
```
2019-08-04T09:35:52 [Info] App.xaml:ApplyAnyOverrideCulture EDDI language setting is: en 
```
In the second log (eddi.log) I see:
```
2019-08-04T09:39:50 [Info] App.xaml:ApplyAnyOverrideCulture EDDI language setting is: Automatic 
2019-08-04T09:39:53 [Info] : VoiceAttack plugin thread culture is: it-IT 
2019-08-04T09:39:53 [Info] VoiceAttackPlugin:SetVAThreadCulture Setting VoiceAttack plugin thread culture to: Automatic 
...
```
Confirm that the first log was with language set in the UI to `Automatic` and the second was with language set to `English` please? The logs are backwards from what I'm expecting to see.

**Comment by mrmauz** [comment] 2019-08-04 17:22
> Confirm that the first log was with language set in the UI to `Automatic` and the second was with language set to `English` please? The logs are backwards from what I'm expecting to see.

i can confirm that, here's the seq:
changed to automatic, installed test6, launched from the installer (at this point EDDI UI was in italian), changed to english, closed, restarted, checked it was still english, closed again, started VA, started game, leaks were present, closed everything, picked up the logs and sent them

**Comment by Tkael** [comment] 2019-08-04 17:32
I'd like the log from the first launch after installing, where you actually changed the language to english. If you haven't restarted EDDI or VA since the last install cycle, it would be `eddi2.log`. If you have, it may be a larger number (but should contain `EDDI language setting set to: en`).

**Comment by mrmauz** [comment] 2019-08-04 18:05
now that you point it's pretty weird: i put it in automatic only for the time need to make the seq you asked me (and changed it back to en in log 4) but it looks like it changed again to automatic while starting from inside VA? as probably suggested before, can this be related to me being unable to access EDDI config from inside VA?

[eddi2.log](https://github.com/EDCD/EDDI/files/3465150/eddi2.log)
[eddi3.log](https://github.com/EDCD/EDDI/files/3465151/eddi3.log)
[eddi4.log](https://github.com/EDCD/EDDI/files/3465152/eddi4.log)

**Comment by Tkael** [comment] 2019-08-04 18:07
Yes it could. I need to see logs from you attempting to open EDDI config while in VA.

**Comment by mrmauz** [comment] 2019-08-04 18:24
i tried it 4 time just to be sure, 2 with the HCS profile active and 2 wityh the EDDI vap active

[eddi.log](https://github.com/EDCD/EDDI/files/3465172/eddi.log)
[eddi1.log](https://github.com/EDCD/EDDI/files/3465173/eddi1.log)

**Comment by Tkael** [comment] 2019-08-06 01:46
Hmm, no logged errors. How are you invoking the EDDI config? 
And do you see any pop up windows or similar when you try to do so?

**Comment by mrmauz** [comment] 2019-08-06 09:38
i have 3 different way to invoke EDDI config: speak to VA ("open EDDI" or in the figure "apri EDDI" a spoken 
command i added), call the shortcut i added to the command (right shift+F5), open the EDDI vap profile config, right click on the "open" command and choosing "execute" from the drop down menu but thew result is always the same: VA hangs for a sec or two, it looses the focus (the title bar goes grey as if something else were opening) but then VA gets the focus back and nothing else happens: no crash, guru meditation or anything.

<img width="461" alt="cattura" src="https://user-images.githubusercontent.com/49005595/62529265-9c396100-b83e-11e9-95eb-d2093fa84078.png">

**Comment by Tkael** [comment] 2019-08-07 02:22
Ok, two things:
1. Please post a screenshot of the plugin action details you are using to invoke EDDI's config.
2. Soon after attempting to invoke EDDI in VoiceAttack, please check your VoiceAttack installation folder for a file called `VoiceAttackFault.txt`. That's the VoiceAttack error log. If it is present in your VoiceAttack installation folder, please attach it here.

**Comment by mrmauz** [comment] 2019-08-07 16:42
is it ok for you if i send you a couple of short videos of the operations i follow?
here it is: https://we.tl/t-iGnBHDMzqc
and here's the pics of the whole thing:
<img width="718" alt="Annotazione 2019-08-07 183836" src="https://user-images.githubusercontent.com/49005595/62640907-d2600900-b942-11e9-97bf-d33514df1580.png">
<img width="712" alt="Annotazione 2019-08-07 183841" src="https://user-images.githubusercontent.com/49005595/62640908-d2600900-b942-11e9-89b1-503ee73049aa.png">

while here's the txt you asked for:
[VoiceAttackFault.txt](https://github.com/EDCD/EDDI/files/3478021/VoiceAttackFault.txt)
weird fact: as you might see from the next pic it hasn't been modified since May
<img width="565" alt="Annotazione 2019-08-07 184216" src="https://user-images.githubusercontent.com/49005595/62641039-1c48ef00-b943-11e9-90f7-6e0c14e24003.png">

**Comment by Tkael** [comment] 2019-08-08 06:22
Ok. I'm assuming that the plugin actions are unchanged from the default EDDI.vap.

You've added `abri eddi` to the command so EDDI recognizes it, but you haven't told VoiceAttack what do do when you say `apri eddi`. You need to add `apri eddi` to the line I indicated in the image below.
![62640907-d2600900-b942-11e9-97bf-d33514df1580](https://user-images.githubusercontent.com/4382539/62679633-f84cd400-b969-11e9-8c4c-44cb7f18c1b2.png)

**Comment by Tkael** [comment] 2019-08-08 06:30
Other ways to invoke EDDI's UI: 
1. Use the English phrase `Configure EDDI` to open the UI.
2. Use the `Execute Another Command (by name)` action to execute the command `Configure EDDI` as an action when you say `apri eddi`.

**Comment by mrmauz** [comment] 2019-08-08 11:36
uuuh, that i hadn't figured out myself, thought the command was itself the call to the config UI. followed your lead and now i can call up the config window with "apri eddi" voice command or "right shift + F5" and well, that's there: EDDI's plugin for VA still had the "automatic" language setting!
but all other changes i made to EDDI was there, from the ivona voice pack to the personality i customized... why so?

**Comment by Tkael** [comment] 2019-08-08 12:30
It has to do with the way the language setting is stored. Essentially, the setting is stored at the app level and not with a config file so the setting is associated with EDDI when run in standalone mode but with the VoiceAttack app when running under VoiceAttack. Using this method of storage helps keep the code for retrieving the setting as simple as possible.

**Comment by mrmauz** [comment] 2019-08-08 13:52
well then... it looks like that was the problem: once changed the settings from inside VA, the leas disappeared!
(and, as i feared, it WAS my fault!)
thanks a lot mate and forgive me for the time i stole you, can we close this one?

**Comment by Tkael** [comment] 2019-08-08 14:07
I want to give some thought to how we store this setting before we do. o7

**Comment by mrmauz** [comment] 2019-08-08 14:22
T'is ok for me, let me know if you need me to idiot proof anything else...
:D

**Closed** 2019-09-18 14:26 UTC
Labels: 6. bug / not up to spec, PR submitted
