### ISSUE TITLE
The cargo monitor does not work, like closed issue #1283

### ISSUE THREAD

**Issue by nepomuk16321** [EDCD/EDDI#1361] opened 2019-06-15 17:53 UTC
## EDDI version in which issue is found
EDDI v3.4.1-rc1

## without Voice Attack

It's the same problem as number #1283.

**Comment by nepomuk16321** [comment] 2019-06-15 18:00
I've tried this:
I have started EDDI then ED and vice versa - no change

I have undocked and have flown out of the station and again into the station and have docked. The station data have been updated, items to buy for a good price have been named. My freight room at EDDI remained empty although I have about 100 drones and 18t tea in the freight room.

How can I help you?

**Comment by Melbar-Kaasom** [comment] 2019-06-16 08:11
My Entry in the Cargo.json:
{ "timestamp":"2019-06-16T07:54:18Z", "event":"Cargo", "Vessel":"Ship", "Count":5, "Inventory":[ 
{ "Name":"drones", "Name_Localised":"Drohne", "Count":5, "Stolen":0 }
 ] }

Triggert in voice Attack with
Say, 'Es sind {INT:Ship limpets carried} Drohnen verfügbar'  (and wait until it completes)

Result: 0 drones

how can I help you?

**Comment by Tkael** [comment] 2019-06-16 16:57
Please provide a verbose log from startup (you'll need to temporarily enable verbose logging then retrieve the log from `%appdata%/EDDI`) and please provide a copy of the matching journal event for that log (from your `[Saved games]/Frontier Developments/Elite Dangerous` folder).

**Comment by Hoodathunk** [comment] 2019-06-16 17:01
the FDEV generated cargo.json file will also be very helpful

**Comment by nepomuk16321** [comment] 2019-06-16 17:56
Ok, I hope I have understood ...
My actions:
* start EDDI, set verbose logging on
* close EDDI
* start Voice Attack with EDDI as plugin
* start ELITE
* ship refuelled
* chaff refuelled
* bought 6 drones (now 110 drones)
* 2t Fujin-tea sold (now 15t)
* with VA ship inventory checked (EDDI: ship variables) result: cargo and limpets "0"
* upload the next 3 files

[Journal.190616193018.01.log](https://github.com/EDCD/EDDI/files/3294396/Journal.190616193018.01.log)

[Cargo.json.txt](https://github.com/EDCD/EDDI/files/3294397/Cargo.json.txt)

[eddi.log](https://github.com/EDCD/EDDI/files/3294398/eddi.log)

I hope this helps.

Thank you, greetings from nepomuk (Mathias)

**Comment by Tkael** [comment] 2019-06-17 00:15
Could we also get a copy of cargomonitor.json from `%appdata%/EDDI`?
If that shows correct numbers, it may be a display problem in the UI more than an issue with actual tracking.

**Comment by Melbar-Kaasom** [comment] 2019-06-17 06:39
As You requested, taking a actual:
[cargomonitor.json.txt](https://github.com/EDCD/EDDI/files/3295511/cargomonitor.json.txt)
[Cargo.json.txt](https://github.com/EDCD/EDDI/files/3295514/Cargo.json.txt)

Ihope it helps.

**Comment by nepomuk16321** [comment] 2019-06-17 07:52
Hi Melbar,
you are quick :-)
My cargomonitor.json has the same content.
[cargomonitor.json.txt](https://github.com/EDCD/EDDI/files/3295757/cargomonitor.json.txt)

**Comment by nepomuk16321** [comment] 2019-06-17 10:07
I don't think it's a display problem. If you query the variables of the ship with VA, the result of the cargo hold is always "0".

**Comment by Tkael** [comment] 2019-06-17 14:07
After seeing your cargomonitor.json files, I agree that it's not a display issue. 

Am I correct in thinking that you are both using EDDI in German? If you switch EDDI to English then restart EDDI, is cargomonitor.json populated correctly?

**Comment by nepomuk16321** [comment] 2019-06-17 16:29
Yes, you're right, I play in German, ELITE and EDDI.
OK, I changed EDDI to English, started ELITE and sold some goods. 
Unfortunately without success. The cargo list in EDDI is empty.
[cargomonitor.json.txt](https://github.com/EDCD/EDDI/files/3297929/cargomonitor.json.txt)

**Comment by Hoodathunk** [comment] 2019-06-17 21:28
@nepomuk16321 I just ran your journal and Cargo files on my development system and the Cargo Monitor built the cargomonitor.json and displayed your cargo data just fine.

I'm at a genuine loss as to what's going on with your computer. Are you running any special drivers/shells which could affect file system caching and such? Is your `Saved Games` folder in a non-standard location?

**Comment by Tkael** [comment] 2019-06-18 00:52
I agree with @Hoodathunk. We're sorry, but we cannot find anything that looks like it is going wrong in the logs and we don't know what could cause cargomonitor.json to not be written correctly for you. Most users are not having this problem.

Since the problem is most likely related to your computer settings, have you tried installing EDDI on a different computer? You can move a journal file (saved at `[your Saved Games folder]/Frontier Developments/Elite Dangerous`) from your current computer to the new computer and inspect the cargomonitor.json file that is created. Which version of Windows are you using?

**Comment by nepomuk16321** [comment] 2019-06-18 06:24
Upps ???
Then why does material monitoring work ?

I am using Win10 Build 17134.829 installed on 10.12.2018 . Updates are enabled.
I'll give you the installation paths later. I have to go to the dentist now :-) :-(
... until later

**Comment by Melbar-Kaasom** [comment] 2019-06-18 07:34
Hi, 
I´m also playing Elite & EDDI in  German.
The trigger of Cargo in VA with
Say, 'Das Schiff {TXT:Ship name} wurde mit {INT:Status cargo carried} Tonnen beladen'  (and wait until it completes)
translation:
Say, 'the ship {TXT:Ship name} has {INT:Status cargo carried} Tons of Load'  (and wait until it completes) answers with the correctly  load. 
Cargo monitor in EDDI is empty.

Im running  Win 10 Pro 64 bit Version 1809 installed 10.January 2019
Build 17763.557

**Comment by Melbar-Kaasom** [comment] 2019-06-18 08:40
changing the language to English doesent  fix the issue.
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/3300553/eddi_issue.zip)
My used Path:
C:\Users\big-boss\Saved Games\Frontier Developments\Elite Dangerous\

**Comment by nepomuk16321** [comment] 2019-06-18 16:23
I have EDDI installed on my notebook. Exactly the same behavior. I asked in the german forum 
if other EDDI users have the same problem. We are currently 3 users who have a problem with
the cargo monitor (I hope, a few more users will reply). 
I can't believe it's due to the Windows settings. The other monitoring systems working fine. 
Ship monitoring works and material monitoring also works.

If you need more information, please let me know. I would like to help solve the problem.

**Comment by Hoodathunk** [comment] 2019-06-18 23:55
@nepomuk16321 

Bear in mind that the monitors and responders are independent entities, utilizing different jsons and data from journal events. Assuming that the Cargo Monitor should work because the Material Monitor does, is not reasonable.

**Comment by nepomuk16321** [comment] 2019-06-19 03:23
Of course you're absolutely right. But I have no idea how the program parts work. The analogy was obvious for me.

**Comment by Tkael** [comment] 2019-06-19 03:56
We think we may have identified a cause for this issue.

**Comment by nepomuk16321** [comment] 2019-06-19 18:15
Really? I don't know. Great, you're the best. :-) :-)

**Comment by Hoodathunk** [comment] 2019-06-25 19:10
@nepomuk16321 @Melbar-Kaasom 
Please verify that the Cargo Monitor is now working for you in 3.4.1-rc3.

**Comment by Melbar-Kaasom** [comment] 2019-06-26 08:15
@Hoodathunk, 
the Cargo monitor is now correctly working! 
In the German Version  I see exclamation marks and hashtags, please see on the attached File.
but it does not really bother, while EDDI is in Background working.
[EDDI-3.4.1-rc3.pdf](https://github.com/EDCD/EDDI/files/3328973/EDDI-3.4.1-rc3.pdf)
Thanks for your great Work!!

**Comment by nepomuk16321** [comment] 2019-06-26 16:00
Hi Melbar,
I wrote the explanation in the german forum.

The "#" and "!" are part of the latest translation.
I wanted to sort the tabs like in the standard language English. Unfortunately, I had no better idea than these characters.

Thanks to Tkael, Hoodathunk and richardbuckle for correcting the Cargo Monitor !!!

Greetings nepomuk

**Comment by Hoodathunk** [comment] 2019-06-26 21:12
Thanks, @. Closing.

**Closed by Hoodathunk** 2019-06-26 21:12 UTC
Labels: PR submitted, need help to reproduce
