### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jokonnoh** [EDCD/EDDI#1626] opened 2019-12-12 19:28 UTC
EDDI version in which issue is found is  3.5.1

1. Accept any kind of missions
2. click  "get route" in mission monitor tab

crash every time

**Comment by Hoodathunk** [comment] 2019-12-12 21:30
Neither the title or the comment is informative.

Have you read the troubleshooting page?
https://github.com/EDCD/EDDI/blob/master/TROUBLESHOOTING.md

**Comment by Tkael** [comment] 2019-12-15 06:37
You can attach EDDI's log file from `%appdata%/roaming/EDDI` if you think that might help us to diagnose this issue. Thanks!

**Comment by Jokonnoh** [comment] 2019-12-15 14:00
Probably i will. I tryed a full removal of EDDI and a new installation. Initial language used with automatic settings (Italian) worked fine. When i changed it with "english", problem came back.So, basically, everytime i click "get route" on missions tab, EDDI crashes to desktop.-------- Messaggio originale --------Da: Brian Wilson <notifications@github.com>Data: dom 15 dic 2019, 07:37A: EDCD/EDDI <EDDI@noreply.github.com>Cc: Jokonnoh <grigioerosso@libero.it>, Author <author@noreply.github.com>Oggetto: Re: [EDCD/EDDI] Crash (#1626)You can attach EDDI's log file from %appdata%/roaming/EDDI if you think that might help us to diagnose this issue. Thanks!

**Comment by Tkael** [comment] 2019-12-21 08:38
Closing due to not having sufficient information to reproduce the error.

**Closed by Tkael** 2019-12-21 08:38 UTC
Labels: need help to reproduce
