### ISSUE TITLE
EDDI does not log my new ships in ship monitor

### ISSUE THREAD

**Issue by MasterZoen** [EDCD/EDDI#350] opened 2018-01-20 12:23 UTC
## EDDI version in which issue found
v.2.4.5

## Steps to reproduce

1. Install Voice Attack.
2. Install EDDI v.2.4.5.
3. Load Elite Dangerous VR: Commander Deluxe Edition.
4. Buy a new ship from a shipyard.
5. Switch to another ship and/or change Ship Name of the new ship in Livery and then switch to another ship.

## Expected
EDDI should register the ship and call it by the name I give it in the Livery.

## Observed
I bought a Cobra Mk. III, EDDI called it a "Cobra 'Mahk' 3". Then I went into livery and changed the name to "Strike King," then I began to outfit the ship. I ran out of funds, so I switched to my trade ship but  EDDI called "Strike King" "Cobra 'Em-key'". EDDI continues to call the ship "Cobra 'Em-Key'" whether I change the Ship Name or switch to and from another ship.

Under ship monitor, this ship is not listed at all.

## Investigation
I bought a second Cobra Mk. III, and EDDI again called it a Cobra 'Mahk' 3," but called the first Cobra Mk III "Unidentified Ship". Then I waited in the new Cobra Mk III doing nothing for ten minutes before giving the command "configure EDDI." Again, there was no listing of the ship in the ship monitor tab. I then went to the Shipyard and switched to my Eagle and EDDI called the Cobra MKIII "Cobra 'Em-key'" while properly calling my Eagle by it's name.

Again, this newly bought ship is not listed under ship monitor.

I then bought a Sidewinder. EDDI called it a "Sidewinder" but called my Eagle "Unidentified Ship". I then waited ten minutes before changing the ship name to "Death Trap." EDDI said that the ship name was registered with the Local Faction. I then switched to my Eagle, and EDDI called the Sidewinder "Sidewinder" while using my Eagle's name.

Again, this newly bought ship is not listed under ship monitor

**Comment by Tkael** [comment] 2018-01-20 15:55
Duplicate of #305.

**Closed by Tkael** 2018-01-20 15:55 UTC

**Comment by MasterZoen** [comment] 2018-01-20 21:41
Just checked to see if this was a duplicate of #305. I don't think it is. #305 is an issue with fuel levels in v.2.4.6-b1, which is a different issue. EDDI doesn't misreport anything about the ship besides the name and the fact it isn't logged in the ship monitor. I've used the Cobra for a number of fights now, and fuel reports are fine, as are ship health and various module damage warnings. Unless your saying that the issue is just that the program is not saving the info correctly?

**Comment by Tkael** [comment] 2018-01-20 21:51
That's correct. The issue has to do with multiple programming threads trying to read and write data to the shipyard and data not being written correctly.
