### ISSUE TITLE
Speech responder priority field display glitches

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/EDDI#1449] opened 2019-08-23 20:11 UTC
As discussed internally, the Priority field of the Speech Responder is showing display glitches upon scrolling down and up agaion.

**Comment by richardbuckle** [comment] 2019-08-23 20:12
Related: #1236

**Comment by richardbuckle** [comment] 2019-08-25 19:01
Fixed in 3.4.2

**Comment by Tkael** [comment] 2020-04-20 16:43
Adding more details and re-opening this for another look.
(Virtualization was previously disabled as a band-aid fix for this)

## EDDI version in which issue is found
3.4.2

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Enable virtualization of the grid in the speech responder.
2. Launch EDDI.
3. Scroll down all the way - no artifacts.
4. Scroll back up - artifacts start appearing.

## Expected
No artifacts / inconsistencies when scrolling up or down the grid.

## Observed
Artifacts. Empty comboboxes particularly.
https://cdn.discordapp.com/attachments/366002840340267018/614186556013412368/unknown.png
https://cdn.discordapp.com/attachments/366002840340267018/614199669026717697/unknown.png

## Investigation
Artifacts start when scrolling back up. 
If you open a script edit window and then close it, the screen refreshes and artifacts disappear

**Comment by JPVenson** [comment] 2020-04-20 20:15
As requested by @Tkael i took a look into the problem and found the root of it.
This behavior is caused by a WPF bug related to the Combobox as stated here:
https://devblogs.microsoft.com/dotnet/net-framework-september-2019-preview-of-quality-rollup/
and related to:
https://stackoverflow.com/questions/56775786/wpf-datagrid-rowvirtualization-problem-with-framework-net-4-8
As this is fixed with .net 4.8 every computer where .net 4.8 is installed at, will *NOT* be able to observe this problem.

There is a wordaround that requires to bind the ItemSource to a non DataContext related path such as using a static binding source. If required i can make this change.

**Comment by Tkael** [comment] 2020-04-21 05:22
Thanks. We're considering whether we want to go ahead with a migration to .NET 4.8 or take you up on that workaround.

**Comment by richardbuckle** [comment] 2020-04-22 00:11
@JPVenson Nice job, many thanks!

I'd prefer to just migrate to .NET 4.8, provided it doesn't cause any issues with VoiceAttack integration. Let's first get all outstanding source code issues squared off and then create a trial branch for .NET 4.8.

**Comment by JPVenson** [comment] 2020-04-22 01:58
@richardbuckle thanks that is appreciated.

I would recommend upgrading to .net 4.8 and also rewrite the whole Editor window with MVVM in mind. That would "solve" 3 current problems:
1. Readability
The current state of the project is not designed with a clear architecture or coding guidance in mind. You are using Bindings to access your properties so why not take the rest of the road and Implement proper MVVM for the UI?
2. Performance Improvements
Its far easier to improve performance on data processing and/or UI when both a separated. 
3. Separation of Concerns 
When UI and data processing logic is separated its simple to work in separated teams/persons to push changes and its easy to perform changes and track individual changes.

i could make a quick MVVM rewrite for this Window for you to decide. That would also include the mentioned "workaround" that i would kind of recommend for design purposes. Such static lists like the Priority list that contains the priority items should be stored in a central location where it is easy to search for and easy to upgrade for the whole application is necessary in future.

**Comment by Tkael** [comment] 2020-04-22 02:38
I'm not opposed to moving the priority list to a more central, static location. It ended up where it did because that was that was best location I could find where I could make the UI work but I appreciate that it's a poor location.

**Comment by JPVenson** [comment] 2020-04-22 02:48
In the end, that should be true for all kinds of global managed lists like:
Squadron Rank, Faction, Power, 
EDDP Monitor States, faction,
Langurages,
Ship roles, models,
etc

**Comment by richardbuckle** [comment] 2020-04-29 00:05
> I would recommend upgrading to .net 4.8 and also rewrite the whole Editor window with MVVM in mind. That would "solve" 3 current problems:
> 
>     1. Readability
>        The current state of the project is not designed with a clear architecture or coding guidance in mind. You are using Bindings to access your properties so why not take the rest of the road and Implement proper MVVM for the UI?
> 
>     2. Performance Improvements
>        Its far easier to improve performance on data processing and/or UI when both are separated.
> 
>     3. Separation of Concerns
>        When UI and data processing logic is separated its simple to work in separated teams/persons to push changes and its easy to perform changes and track individual changes.
> 
> 
> i could make a quick MVVM rewrite for this Window for you to decide. That would also include the mentioned "workaround" that i would kind of recommend for design purposes. Such static lists like the Priority list that contains the priority items should be stored in a central location where it is easy to search for and easy to upgrade for the whole application is necessary in future.

I am completely in favour of moving to 4.8 and, coming from the Apple MVC background, I would very much like to learn about MVVM from an experienced practioner.

What I *would* say is let us first get any work in progress squared off.

**Comment by JPVenson** [comment] 2020-04-29 12:32
i could give you a quick introduction outside of github if you like to.

i see no harm in rewriting the app in MVVM as an ongoing task, that would help a lot of contributors to learn about it.

**Comment by richardbuckle** [comment] 2020-05-01 00:16
I'm interested in learning about MVVM from someone who has professional experience.

I think we all have preferences for learning: I learn best from text whereas often people learn better from video or from example.

If you can start by pointing to links that define and illustrate what MVVM is, we can take it from there.

**Comment by JPVenson** [comment] 2020-05-01 00:43
I understand that and i prefer a vocal introduction into the matter with text resources after to allow everyone retain that knowledge. Part of my profession is MVVM training and i can send you my "standard" handout if you like to. It contains all msdn references that i would recommend reading. As this is part of *my* companies resources i am not keen to post it publicly but i would send you a copy.

If you would like to have just the online resources please say so.

**Comment by Tkael** [comment] 2020-10-31 23:04
Closing as resolved by #1772.
@JPVenson I'm interested in learning more about MVVM if those materials are still on offer.

**Closed by Tkael** 2020-10-31 23:04 UTC
Labels: 6. not up to spec, user interface

**Comment by JPVenson** [comment] 2020-11-01 01:37
@Tkael sure, just contact me at info@jean-pierre-bachmann.dev i can send you some documents and slides in englisch and if you like to we can go through them via Skype/Discord etc.
