### ISSUE TITLE
Application closes after starting, log with error: "Newtonsoft.Json.JsonSerializationException: Error getting value from 'shortname' on 'EddiEvents.CarrierJumpRequestEvent'."

### ISSUE THREAD

**Issue by tripofgames** [EDCD/EDDI#1832] opened 2020-06-19 19:40 UTC
## EDDI version in which issue is found
3.5.3-b3

## VoiceAttack version in which issue is found (as applicable)
N/A

## Steps to reproduce
1. Start EDDI
2. Wait for a couple seconds
3. Application ends by itself

## Expected
Application to keep working

## Observed
Application ends.

## Investigation
I first checked the AppData folder and cleaned it as seeing in other threads with similar issues (application closing), it didn't solve the issue and the log message is still the same.
Log:
2020-06-19T19:31:08 [Info] EDDI:eventJumped Jumped to Col 285 Sector DC-K a38-5 
2020-06-19T19:31:08 [Warning] JournalMonitor:ParseJournalEntry EDDI has no handler for event type 'CargoTransfer'./r/nRaw event:/r/n{ "timestamp":"2020-06-19T01:10:56Z", "event":"CargoTransfer", "Transfers":[ { "Type":"lowtemperaturediamond", "Type_Localised":"Low Temperature Diamonds", "Count":182, "Direction":"tocarrier" } ] } System.NotImplementedException: EDDI has no handler for event type 'CargoTransfer'.
   at EddiJournalMonitor.JournalMonitor.ParseJournalEntry(String line, Boolean fromLogLoad)
2020-06-19T19:31:08 [Info] EDDI:eventJumped Jumped to Col 285 Sector CC-K a38-2 
2020-06-19T19:31:09 [Info] Logging:ExceptionHandler Reporting unhandled exception, anonymous ID 4f68825c-0251-4a89-9348-b487bbf5d033:Newtonsoft.Json.JsonSerializationException: Error getting value from 'shortname' on 'EddiEvents.CarrierJumpRequestEvent'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at EddiEvents.CarrierJumpRequestEvent.get_shortname()
   at Getshortname(Object )
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Eddi.EDDI.eventHandler(Event event)
   at Eddi.EDDI.dequeueEvent()
   at Eddi.EDDI.<enqueueEvent>b__135_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart() 
2020-06-19T19:31:09 [Info] EDDI:Stop EDDI 3.5.3-b3 stopped 
2020-06-19T19:31:09 [Info] EDDI:Start Starting keepalive for EDDP monitor 
[eddi.log](https://github.com/EDCD/EDDI/files/4806445/eddi.log)

**Comment by Tkael** [comment] 2020-06-19 21:22
Duplicate of #1819. Please follow the instructions there for a temporary resolution. 
A pull request has already been approved to correct this for the next release.

**Closed as completed by Tkael** 2020-06-19 21:22 UTC
Labels: duplicate

**Comment by Tkael** [comment] 2020-06-19 21:36
See also https://github.com/EDCD/EDDI/issues/1819#issuecomment-646868827
