### ISSUE TITLE
Problems with Pleiades Sector PD-S b4-0 / Ieyasu Dock

### ISSUE THREAD

**Issue by lwt-pressy** [EDCD/EDDI#636] opened 2018-06-09 07:16 UTC
## EDDI version in which issue found

v3.0.1-b4

## Steps to reproduce

I want to enter  Pleiades Sector PD-S b4-0 / Ieyasu Dock as Home System. Ieyasu Dock is not accepted as station, Also when I jump in the system EDDI says it is unpopulated even though it has a population of 1,200,000 and the orbital station is not announced.

## Expected
Station is valid as home station and data is anounced at jump in.

## Observed
see above

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment] 2018-06-09 08:36
Thanks for the report, but I'm closing this as a duplicate of #97 (to keep the issues list as clean as possible). There's a known, albeit uncommon, issue wherein the backend server we use for this data is not always up to date. This seems to be more common around the Pleiades. Since we don't control that back-end server, we have been studying options for migrating away from it to another solution.

**Closed by Tkael** 2018-06-09 08:36 UTC
