### ISSUE TITLE
Possible bug with {TXT:Ship model}

### ISSUE THREAD

**Issue by FireSammy** [EDCD/EDDI#2502] opened 2023-01-23 14:45 UTC
## What's Wrong (please be as specific as possible)
I have certain VA commands based on the {TXT:Ship model}, which are currently not working

### Expected
[Describe what you expected to happen]
It used to work just fine and I didn't get any problems with these VA commands

**Comment by Tkael** [comment] 2023-01-24 08:09
Duplicate of #2482.

**Closed as completed by Tkael** 2023-01-24 08:09 UTC
Labels: duplicate
