### ISSUE TITLE
Feature Request - Multiple Commander Accounts

### ISSUE THREAD

**Issue by TomoSco** [EDCD/EDDI#2101] opened 2021-01-30 12:14 UTC
Love the program and use it all the time but

Would it be possible to add profiles to the program, I have 2 frontier accounts and would like to use eddi on both without having to change all my api keys everytime.

Just a suggestion and thanks again for a great program

**Comment by Tkael** [comment] 2021-01-30 22:38
Thanks for the feedback. Unfortunately, more is affected than just API keys. This is a duplicate of an old ticket #505 that has been under consideration for some time so I'm going to go ahead and close this ticket in favor of that one.

**Closed as completed by Tkael** 2021-01-30 22:38 UTC
Labels: duplicate
