### ISSUE TITLE
EDDI not starting first on first time usage

### ISSUE THREAD

**Issue by dallday** [EDCD/EDDI#960] opened 2018-11-24 22:31 UTC
## EDDI version in which issue found
Version 3.1.0

## Steps to reproduce

This was an install of EDDI on a new machine. Ran the install using EDDI-3.1 and installed it to the standard Voice Attack directory.

## Expected
Tried to start EDDI to get the configuration screen.

## Observed
Nothing appeared on the screen.
Error messages were logged in Windows Application Event Log 

## Investigation
Checked the error ( see Error1.rtf ) and this complained about file not found at Utilities.Logging.incrementLogs. Checked the source code and this was trying to check the log files in the log directory. This I understand is %APPDATA%\EDDI. I checked and the folder did not exist. 
I created the folder and then EDDI started,

There is no check in the code to endure that the %APPDATA%\EDDI directory actually exists, or to create it. Also there seems to be no error trapping at the main level.

[Error1.txt](https://github.com/EDCD/EDDI/files/2612631/Error1.txt)

**Comment by Tkael** [comment] 2018-11-25 02:54
Thanks for the report. This is a known issue (sorry about that) and a pull request to correct it has already been submitted. PR #952.

**Comment by Tkael** [comment] 2018-11-25 02:55
Closing as a duplicate of #950.

**Closed by Tkael** 2018-11-25 02:55 UTC

**Comment by dallday** [comment] 2018-11-25 09:18
Thanks for the fast response - all working fine now.
