### ISSUE TITLE
Material monitor issues with unknown/thargoid materials/data

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDDI#83] opened 2017-09-17 22:50 UTC
I stocked up on Thargoid data/materials in preparation for 2.4, and the materials monitor is showing some issues:

![image](https://user-images.githubusercontent.com/25147462/30525654-e15fe170-9c0a-11e7-9259-17984ea24269.png)

Basically, all unknown materials/data of 2.3 will be Thargoid in 2.4; the exception are unknown artefacts (become thargoid sensors) and unknown fragments (become sensor fragments).  This only affects the in-game display, the names in the journal such as tg_residuedata) stay unchanged.

If you check the screenshot, you will find the new names, some old names, and some raw names.  Additionally, all the old names are of type "unknown" rather than material or data, but have the correct numbers.

**Comment by Tkael** [comment] 2017-09-18 04:15
This comes down to doubling up entries in the materialmonitor.json file.

**Comment by Syrrianyl** [comment] 2017-09-18 06:18
So, to remove the problem the user must open the materialmonitor.json file and remove one of the doubling entries manyually, or delete the materialmonitor.json and after restart EDDI and normaly all the material return as human reading (the problem is when all min, max and desired are completed)


What we must look is if the problem come back after.


I just realise that when I change from my EDDI with french translation to my work with the EDDI in english, finally I have all the materials in french and in english. The material in the language not used are all "unknown". In the final translation work I must create a new json file for material like a materialmonitor_fr.json to remobe the problem.

**Comment by richardbuckle** [comment] 2017-09-21 09:13
Good question. I shall investigate.

**Comment by Tkael** [comment] 2017-10-07 02:26
This issue arose because the json uses humanized names and falls back to ednames whenever humanized names are not available. The data will always include the ednames, so I think the json should be revised to use ednames as keys, with the humanized names becoming optional extras to the data.

**Comment by Tkael** [comment] 2017-10-24 01:11
Fixed by the latest release.

**Closed by Tkael** 2017-10-24 01:11 UTC
Labels: 6. bug / not up to spec
