### ISSUE TITLE
Norton marks EDDI-3.4.3.exe as threat

### ISSUE THREAD

**Issue by JavaJoeCoffee** [EDCD/EDDI#1484] opened 2019-09-11 02:24 UTC
## EDDI version in which issue is found
EDDI 3.4.0

## VoiceAttack version in which issue is found (as applicable)
1.7.5

## Steps to reproduce
Download 3.4.3 from app update or GitHub itself

## Expected
Download and install as normal

## Observed
EDDI-3.4.3.exe is flagged by Heur.AdvML.B  and gets marked as threat and is deleted by Norton 

## Investigation
Consistent over multiple downloads. Never seen before 3.4.3

**Comment by Tkael** [comment] 2019-09-11 02:42
Thanks for reporting, but this is a duplicate of #1460. 
We really don't know and can't control for Norton's detection algorithm.

**Closed by Tkael** 2019-09-11 02:42 UTC
Labels: duplicate
