### ISSUE TITLE
Multi-Pilot Enhancement

### ISSUE THREAD

**Issue by Timnus** [EDCD/EDDI#1732] opened 2020-04-05 23:24 UTC
## EDDI version in which issue is found
3.5.2

## VoiceAttack version in which issue is found (as applicable)
N/AQ

## Steps to reproduce
1. start EDDI with main commander
2.  spend up to 1/2 hour changing EDDI with optional Commander

## Expected
read into for 2nd CMDR

## Observed
Works ok just take a wallop of time when you change CMDR due to API key changes. 

## Investigation
[Any investigation you have done, regression tests against earlier versions, etc]

**Comment by Tkael** [comment] 2020-04-06 02:02
I think this is a duplicate of #505, though once again the initial ticket isn't very clear. 
EDDI does not currently currently support multiple commanders and settings are stored per Windows account. Consequently, the best option for keeping multiple commanders configured is currently to use separate Windows accounts for each commander.

**Closed by Tkael** 2020-04-06 02:02 UTC
Labels: duplicate

**Comment by Timnus** [comment] 2020-04-06 06:43
how do i do that? 
i only have one windows

Have a Wonderful Day!!!
Timothy Deane 

    On Sunday, April 5, 2020, 9:02:30 PM CDT, Brian Wilson <notifications@github.com> wrote:  
 
 


I think this is a duplicate of #505, though once again the initial ticket isn't very clear.
EDDI does not currently currently support multiple commanders and settings are stored per Windows account. Consequently, the best option for keeping multiple commanders configured is currently to use separate Windows accounts for each commander.

**Comment by Timnus** [comment] 2020-04-06 07:33
I just now figured out what you mean. another windows login. that would mean my installing everything again. 8 hours. and i dont have the disk space for that. 

Have a Wonderful Day!!!
Timothy Deane 

    On Sunday, April 5, 2020, 9:02:30 PM CDT, Brian Wilson <notifications@github.com> wrote:  
 
 


I think this is a duplicate of #505, though once again the initial ticket isn't very clear.
EDDI does not currently currently support multiple commanders and settings are stored per Windows account. Consequently, the best option for keeping multiple commanders configured is currently to use separate Windows accounts for each commander.

**Comment by Tkael** [comment] 2020-04-06 08:50
No need to reinstall everything. You would just need to set up a secondary local account. https://support.microsoft.com/en-us/help/4026923/windows-10-create-a-local-user-or-administrator-account

**Comment by Timnus** [comment] 2020-04-14 17:20
tried it just as you said. NOTHING i use is installed. just basic Microsoft stuff. now what?

**Comment by Tkael** [comment] 2020-04-14 17:42
Open and configure EDDI under the new Windows account.

**Comment by Timnus** [comment] 2020-04-14 22:41
its NOT there!
i cannot install it either.
