### ISSUE TITLE
EDDN responder in invalid state at Eagle Sector IR-W d1-117

### ISSUE THREAD

**Issue by BillKills974** [EDCD/EDDI#1137] opened 2019-01-29 00:01 UTC
## EDDI version in which issue found
Version 3.3.3, issue found in both VA plugin and standalone.

## Steps to reproduce

1. I jump to Eagle Sector IR-W d1-117
2. Dock to Eagle's Landing

## Expected
Nothing visible in-game, data synced with EDSM and EDDN

## Observed
EDDI complains about EDDN responder in an invalid state and unable to send messages, try to jump out of the system and back, or log out and log back in. Data in EDSM is not synced for this sector (the current sector stays the previous one).

## Investigation
Tried a lot of times to jump out and back, or log out and back in, to no avail. Activated debug log in EDDI, found an InvalidCastException just before the warning ("EDDNReponder: CheckLocationData The EDDN responder is in an invalid state and is unable to send messages…")
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/2805430/eddi_issue.zip)

**Comment by Tkael** [comment] 2019-01-29 02:06
This is a duplicate of prior reports, and something we've been working to correct since version 3.3.3 was released. Please try the newest version available [here](https://github.com/EDCD/EDDI/releases) and report again if you see the same issue on that version. Thanks for the report!

**Closed by Tkael** 2019-01-29 02:06 UTC
Labels: duplicate
