### ISSUE TITLE
Not recognizing when cargo/haulage has been sold/unloaded for mission

### ISSUE THREAD

**Issue by billgoll** [EDCD/EDDI#246] opened 2017-11-19 20:22 UTC
## Steps to reproduce
Session started with commodities (haulage) in cargo hold for several accepted missions
EDDI says "You can sell your <commodity> here but check for best profit"  (or something like that)

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]
As the commodities are disposed of by completing the missions, I would expect EDDI to notice that the commodities are no longer on board and to stop informing me about potential profit opportunities.

## Observed
[describe what happened instead]
After missions are completed and the commodities have been disposed of, when landing at other stations, EDDI continues to give the same message even though those commodities are no longer on board.

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]
Have noticed this several times.  Does not seem to be an issue when commodities are purchased directly from the local market.

**Comment by Tkael** [comment] 2017-11-19 23:33
Duplicate of #47, currently in progress.
@Hoodathunk Please confirm?

**Comment by Hoodathunk** [comment] 2017-11-20 20:49
Yes, this is a dupe.

@billgoll This has been a problem since before @jgm took a break from EDDI. Cargo is only updated during sign-in, with the 'Cargo' event.

@jgm started building a 'Cargo Monitor' but didn't finish it. I picked it up a month or so back and in the process of tidying it up.

Worst case scenario is release shortly after the holidays.

**Comment by Tkael** [comment] 2017-11-21 02:55
Ok. Closing as a duplicate. Please look to #47 for updates on this issue.

**Closed by Tkael** 2017-11-21 02:55 UTC
Labels: duplicate
