### ISSUE TITLE
Crash on fleet carrier jump setting

### ISSUE THREAD

**Issue by Jwh1o1** [EDCD/EDDI#1822] opened 2020-06-13 22:11 UTC
## EDDI version in which issue is found
[3.5.3 b3]

## VoiceAttack version in which issue is found (as applicable)
[1.8.5]

## Steps to reproduce
Starting voice attack.

## Expected
voice attack to start up

## Observed
voice attack errors out and closes

## Investigation
setting the fleet carrier jump crashes the thing

**Comment by Jwh1o1** [comment] 2020-06-13 22:12
[eddi1.log](https://github.com/EDCD/EDDI/files/4775586/eddi1.log)

**Comment by Jwh1o1** [comment] 2020-06-13 22:12
[eddi.log](https://github.com/EDCD/EDDI/files/4775587/eddi.log)

**Comment by Tkael** [comment] 2020-06-14 01:33
Duplicate of #1819. Please follow the instructions there for a temporary resolution.

**Closed as completed by Tkael** 2020-06-14 01:33 UTC

**Comment by Tkael** [comment] 2020-06-19 21:35
See also https://github.com/EDCD/EDDI/issues/1819#issuecomment-646868827
