### ISSUE TITLE
Search and rescue script not mentioning commodities when handing them in.

### ISSUE THREAD

**Issue by JCalvertJoshua** [EDCD/EDDI#597] opened 2018-05-26 09:50 UTC
## EDDI version in which issue found
3.0.1 Beta 4 (also beta 3)

In the CG from last week I handed in Occupied Escape Pods but Eddi only mentions I handed in a number of s (blanks) like this:
"127 s recovered in exchange for over 4 million credits"
EDDI knows what they are because when I recovered them it said:
"Occupied Escape Pod now on board."

After the CG was over I looked at the script and the Test Script also gave just this:
"2 s recovered for on the way to 5 and a half thousand credits"

It looks like it doesn't recognize the commodity and just adds an s to the blank because there's more then 1.

When I change the event.commodity.name in event.commodity like this:
|elif event.commodity.name = "Occupied Escape Pod":
|elif event.commodity = "Occupied Escape Pod":
(and the same for the other commodities)
it seems to work when I use test script:
"2 occupied escape pods salvaged for on the way to 5 and a half thousand credits"

**Comment by richardbuckle** [comment] 2018-05-27 20:31
Duplicate of #602

**Comment by Tkael** [comment] 2018-05-29 07:01
Closing as a duplicate. 
Relevant journal entries documented in #602.

**Closed by Tkael** 2018-05-29 07:01 UTC
Labels: 6. bug / not up to spec, duplicate
