### ISSUE TITLE
EDDI uses out-of-date cargo information

### ISSUE THREAD

**Issue by Rode-Ven** [EDCD/EDDI#487] opened 2018-04-14 14:06 UTC
## EDDI version in which issue found
v.3.0.0-rc3

## Steps to reproduce
- Start EDDI
- Start E:D
- dock at a station and buy some goods
- travel to another system
- dock at station and sell goods
- travel to another system
- dock at station with a good price for the goods you sold previously (so your cargo hold is empty)

## Expected
EDDI will remain silent

## Observed
EDDI announces that I can sell my cargo with a profit, using the numbers from the cargo already sold a station ago.

## Investigation
It seems that EDDI does not manage cleared cargo correctly.
The same seems true for limpets (which happen to take up cargo space as well), where EDDI complains about not having enough limpets aboard despite the fact that they were restocked a while ago.

**Comment by Hoodathunk** [comment] 2018-04-14 14:54
EDDI doesn’t ‘manage’ cargo at all, at the current revision. The ‘Cargo Monitor’ was a WIP when jgm left the project. In a previous iteration of the cAPI, FDEV included real-time cargo data, but was ultimately removed. At present, EDDI only accepts cargo updates during initial login from the ‘Cargo Inventory’ event. No subsequent events during a play session at acted upon. TL,DR... EDDI is working as intended.

Is this annoying? Absolutely! Cargo Monitor was pretty much an empty husk and I’ve been working on a fully featured replacement for some months and very close to being finished. We will be releasing 3.0.0 within a week and I expect the updated Cargo Monitor to be close on its heels as 3.0.1.

Refer to Issue #47.

**Comment by Tkael** [comment] 2018-04-14 19:06
Closing as a duplicate of #47 & #52. @Hoodathunk is actively working on this issue. Thanks for the report. :-)

**Closed by Tkael** 2018-04-14 19:06 UTC
Labels: duplicate
