### ISSUE TITLE
Can't download EDSM log, EDDI just crashes out

### ISSUE THREAD

**Issue by Taomyn** [EDCD/EDDI#540] opened 2018-05-10 19:30 UTC
## EDDI version in which issue found
3.0.1-b2, standalone

## Steps to reproduce
1. Start EDDI
2. Press button to download/process logs

## Expected
Logs to download/process

## Observed
Gets to about 100 of over 4000 and application crashes

## Investigation
Enabled debugging, here is the log
[eddi.log](https://github.com/EDCD/EDDI/files/1992982/eddi.log)

**Comment by Tkael** [comment] 2018-05-11 04:58
Confirmed. Looks like a change in the data structure needs to be made backwards compatible needs so that we can read and manipulate legacy data from the sql database.
Data structure was
```
        {
            "name": "ProgenitorCells",
            "category": null,
            "avgprice": null,
            "rare": null,
            "buyprice": null,
            "stock": null,
            "stockbracket": null,
            "sellprice": 6561,
            "demand": 17,
            "demandbracket": null,
            "StatusFlags": null,
            "EDDBID": -1,
            "EDName": null
        },
```
and is
```
        {
            "definition": {
                "edname": "ProgenitorCells"
            },
            "invariantName": "Progenitor Cells",
            "localizedName": "Progenitor Cells",
            "name": "Progenitor Cells",
            "buyprice": null,
            "stock": null,
            "stockbracket": "",
            "sellprice": 7279,
            "demand": 56,
            "demandbracket": "",
            "StatusFlags": [],
            "EliteID": 0,
            "EDDBID": 36,
            "category": "Medicines",
            "avgprice": 6779,
            "rare": false
        },
```

**Comment by Tkael** [comment] 2018-05-17 00:59
The precise exception is as follows:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=EddiDataDefinitions
  StackTrace:
   at EddiDataDefinitions.CommodityMarketQuote.get_invariantName() in C:\Users\Brian\source\repos\EDDI\DataDefinitions\CommodityMarketQuote.cs:line 13
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
```
The object definition is not being set correctly. The precise commodity that is triggering this error appears to be `Limpets` (e.g. `Drones`).

**Comment by Tkael** [comment] 2018-05-17 01:03
To replicate this error, attempt to obtain EDSM logs in version 3.0.1-b2 with data in your sqlite database from 3.0.0 or earlier.

**Comment by richardbuckle** [comment] 2018-05-20 19:45
PR merged

**Closed by richardbuckle** 2018-05-20 19:45 UTC
Labels: 3. crash / lockup, PR submitted
