### ISSUE TITLE
EDD errors when landing at stations

### ISSUE THREAD

**Issue by billgoll** [EDCD/EDDI#183] opened 2017-10-26 03:17 UTC
## Steps to reproduce
When landing at a station, EDDI indicates that there are EDD errors and to submit a log file.  This seems to happen at all stations.  I do have Elite dangerous market connector running as well as an HCS voice pack (ASTRA).  I'm running EDDI 2.4.2 under voice attack.  the problem started after the update to 2.4.2

1. [give the fullest and most reproducible steps you can]
2. [the more reproducible, the better our chances of fixing it]

## Expected
[describe what you expected to happen]
?  No error message.

## Observed
[describe what happened instead]
[eddi_issue.zip](https://github.com/EDCD/EDDI/files/1416843/eddi_issue.zip)

## Investigation
[any investigation you have done, regression tests against earlier versions, etc]
Nothing.

**Comment by billgoll** [comment] 2017-10-26 03:17
[Journal.171023195627.01.log](https://github.com/EDCD/EDDI/files/1416853/Journal.171023195627.01.log)

**Comment by Hoodathunk** [comment] 2017-10-26 14:21
The error announcement is intentional, to correct discrepancies between EDDI and recent (undocumented) changes by FDEV with commodity naming.

You correctly included the eddi_issue.zip file, unfortunately, we're having a separate issue were the zip file is empty. If you could provide the eddi.text log file in your /user/AppData/Roaming/EDDI folder, that would be very appreciated. At present, this our only means of collecting the discrepant data.

In the next update (soon), I will be disabling the error announcement. In theory it sounded like a good thing in order to make EDDI better for the community, but in practice, it's annoying and immersion breaking. My apologies... we will figure out another way to collect this data.

**Comment by billgoll** [comment] 2017-10-27 01:48
[eddi.log](https://github.com/EDCD/EDDI/files/1420536/eddi.log)

**Comment by ericlebail** [comment] 2017-10-30 19:53
[eddi.log](https://github.com/EDCD/EDDI/files/1428548/eddi.log)
File with one error on a missing module.

**Comment by richardbuckle** [comment] 2017-10-31 22:13
Closing as duplicate of #181.

**Closed by richardbuckle** 2017-10-31 22:13 UTC
Labels: 5. priority / painful, 6. bug / not up to spec, duplicate
